### ISSUE TITLE
Upload CSV file using cypress

### ISSUE THREAD

**Issue by BavithraDuraisamy** [abramenal/cypress-file-upload#116]
### Current behavior:

I have a feature to upload CSV files in my application. and I'm trying the below lines of code. but it says that [cypress-file-upload error]: One or more field is invalid within given file(s).
Please look into docs to find supported "fileOrArray" values

### Code Snippet
    cy.server()
    cy.route('POST', 'https://somesite/upload', 200).as('upload')
    cy.get('input[type="file"]').upload(
      {
        fileContent: 'file content',
        fileName: 'SmallTapeCrackerTestFile.csv',
        contentType: 'text/csv',
      },
      { subjectType: 'input' }
    )

    // make sure upload has happened
    cy.wait('@upload')

**Comment by abramenal** [comment]
Hi @BavithraDuraisamy 
Thanks for submitting the issue!

As mentioned in the error you see, `fileContent` should be a valid file object (usually obtained from `cy.fixture`), not just a string. Please take a look on the recipes in the repo for more usage examples.

Thanks!

**Comment by tiagofernandez** [comment]
I stumbled upon the same issue after upgrading to `3.5.1`, so in my case I just sticked with `3.1.2`.

**Comment by abramenal** [comment]
@tiagofernandez can you please describe your issue? The original issue is about improper API usage.
Feel free to create a new issue and link with this one if you feel they are related.
Thanks!

**Comment by tiagofernandez** [comment]
@abramenal IIRC after upgrading all my packages, tests I had involving file uploads started failing with the same error message as in this issue's description. As I wasn't upgrading this package for any particular reason, I decided to just downgrade it back. I'll create a detailed issue next time I try.
