### ISSUE TITLE
[Bug] Files upload are blank

### ISSUE THREAD

**Issue by atemor** [abramenal/cypress-file-upload#117]
### Current behavior:

When I upload a file (.PDF) the file is upload but the PDF is blank.

### Desired behavior:

I Want to upload the PDF as it exist

### Steps to reproduce: (app code and test code)

```
When("I enter the Visite médicale au travail information", () => {
    const fileName = "cv644.pdf";
    cy.fixture(fileName).then(fileContent => {
      cy.xpath('//input[@class="file-input"][1]').upload({
        fileContent,
        fileName,
        mimeType: "application/pdf"
      });
    });
    cy.waitUntil(() =>
      cy.xpath('//i[@class="icon-check"][1]').should("be.visible")
    );
    cy.get("[id^=day-JJ]").type("25");
    cy.get("[id^=month-MM]").type("08");
    cy.get("[id^=year-AAAA]").type("2025");
    cy.get("[id^=profession-crivezici-Mtiersconcerns]").type("Boulanger");
    cy.xpath('//div[@role="menu"]/.//span[@role="menuitem"]')
      .contains("Boulanger")
      .click();
    cy.xpath('//button[@type="button"][1]')
      .eq("4")
      .click();
  });
```

The PDF is in my fixture file

**Comment by abramenal** [comment]
Hi @atemor 
Thanks for submitting the issue!
Which `cypress` and `cypress-file-upload` you're using?
How do you read PDF file content after upload?

**Comment by atemor** [comment]
Hello :)

@abramenal 
Here are the version
cypress-file-upload : 3.3.4
cypress  3.5.0

T read the content file I do it manually in the back office of the app

**Comment by abramenal** [comment]
@atemor 

There is no thing that could be related to this package itself as it does not modify file contents in any way.
Here are some possible reasons you seeing the issue:

- `cy.fixture` returns empty file contents – this can be related to some specific file encoding which should be passed manually both to `cy.fixture` and `.upload` method
- there is some timing issue, like you try to see file contents until it's fully loaded – see `cy.wait` and fetch aliases

**Comment by atemor** [comment]
Hello,
I use cy.wait and i have the same issue.
The PDF is loaded but it's still an empty PDF :(
How can I work on the file encoding ?

**Comment by atemor** [comment]
@abramenal usualy, when I do the test manualy, I use the same file and it work like a charm.
Thanks anyway, I'll try to catch a dev in my team

**Comment by abramenal** [comment]
@atemor 
Please do and in case if he or she won't be able to fix that, let this dev come here and create an issue so we can figure out what is the issue.
Cheers!

**Comment by eflorent-ineat** [comment]
Same problem here, a diff on the uploaded file shows that at some point it is changed, there is an encoding issue. I am pretty sure it is around the way encoding is done, but have no doc, help or solution yet.
