### ISSUE TITLE
please provide recipes for laravel blade file upload

### ISSUE THREAD

**Issue by toshim45** [abramenal/cypress-file-upload#118]
Hi,
I try to upload image file, but always got
```
[cypress-file-upload error]: One or more field is invalid within given file(s).
Please look into docs to find supported "fileOrArray" values
```
here is my laravel blade code, just common file upload html
```
<form method='post' action='' enctype="multipart/form-data">
          Select file : <input type='file' name='file' id='company-logo-file' class='form-control'><br>
          <input type='button' class='btn btn-info' value='Upload' id='company-logo-upload-button'>
        </form>
```

and this is my spec

```
        cy.fixture(fileImage, 'base64').then(fileContent => {
            cy.get('#company-logo-file').upload({
                fileContent,
                fileImage,
                mimeType: 'image/png',
                encoding: 'base64'
            }, {
                subjectType: 'input'
            })
            cy.contains(fileImage);
        })
```

I use cypress 3.5.0 with cypress-file-upload 3.4.0

I already followed [recipes](https://github.com/abramenal/cypress-file-upload/tree/a0cf1233cee799492ea0e721a5645df426814eec#recipes) (i think the closest one is react html5 input, but still got same error)

Thanks :)

**Comment by abramenal** [comment]
Hi @toshim45 
Thanks for submitting the issue!

As mentioned in the error you see, your first argument of `upload` method is invalid. It accepts only the following fields: `fileContent`, `fileName`, `mimeType`, `encoding`.
You're trying to pass unknown `fileImage` and do not pass `fileName`.

https://github.com/abramenal/cypress-file-upload/tree/master#api

Let me know if you need any further help.
If that works, I think it would be beneficial for further users to have laravel recipe, but I don't have experience in that so it could be your first contribution to this project (of course if you have some time and passion). I can assist with anything which is related to this package and recipe creation.

Cheers,
Paul

**Comment by toshim45** [comment]
thx @abramenal for fast response.

actually fileImage is just file name, at the top of source

```
const fileImage = 'cy.png'
```

**Comment by toshim45** [comment]
ok I resolve this by renaming the variable `fileImage` to `fileName`
Thanks

**Comment by abramenal** [comment]
@toshim45 if you want to go with original variable name:
````
const fileImage = 'cy.png';
...
cy.upload({
   ...
   fileName: fileImage,
});
```
