### ISSUE TITLE
[Bug] -- cypress-file-upload does not work with Electron or headless Chrome during cypress tests

### ISSUE THREAD

**Issue by lunxiao** [abramenal/cypress-file-upload#12]
### Current behavior:

I saw the Wrap but not the Trigger. File is not put into the file loader.

### Desired behavior:

The file is attached to file loader.

### Steps to reproduce: (app code and test code)

This is the code used:
` cy.fixture('test.csv', 'ascii').then(content => {
        cy.get('[id=fileUpload]').upload(content, 'test.csv', 'application/plain');
        cy.wait(10000);
     });`
### Versions

Windows 10, Electron 59

**Comment by abramenal** [comment]
Hi @lunxiao 
Thanks for contribution!

Can you please also describe your app setup: framework/library, element with id: fileUpload nature (is it a HTML input or some component?
If you can make a code snippet with your source code that can help a lot in finding the cause of issue you're facing.

**Comment by oliverodaa** [comment]
I am also experiencing this problem.

The following code **does** work with the Cypress UI, but not with headless. In other words:
- `yarn run cypress open` works 👍
- `yarn run cypress run` fails 👎 

```js
cy.fixture('file.json').then(content => {
  const base = Buffer.from(JSON.stringify(content)).toString('base64');

  cy
    .get('.SelectDocument__drag-drop-area')
    .upload(base, 'file.json', 'application/json');

  cy
    .get('button')
    .contains('Upload and continue')
    .click();
});
```

The error is:
```
CypressError: Timed out retrying: Expected to find content: 'Upload and continue' within the element: <button> but never did.
```

**Comment by oliverodaa** [comment]
Here is a snippet that can reproduce the issue:

```js
context('App', () => {
  it('does stuff', () => {
    cy.visit('https://o10k74xq06.codesandbox.io/');

    cy.fixture('huge.json').then(content => {
      const base = Buffer.from(JSON.stringify(content)).toString('base64');

      cy.get('#drag-drop-area').upload(base, 'huge.json', 'application/json');

      cy
        .get('div')
        .contains('File dropped!')
        .click();
    });
  });
});
```

If you run it with `yarn run cypress open`, the test will pass.

If you run it with `yarn run cypress run`, the test will fail.

---

**Note**: the page being visited above is a CodeSandbox example. You can see the source code at https://codesandbox.io/s/o10k74xq06

Actually... Here's the source code anyway, just in case you can't visit the link.
```js
import React from "react";
import ReactDOM from "react-dom";

class App extends React.Component {
  state = {
    file: null,
    isHovering: false
  };

  render() {
    const { file, isHovering } = this.state;
    return (
      <div>
        <div
          id="drag-drop-area"
          onDragOver={e => {
            e.preventDefault();
            this.setState({ isHovering: true });
          }}
          onDragLeave={e => {
            this.setState({ isHovering: false });
          }}
          onDrop={e => {
            e.preventDefault();
            this.setState({ file: "File dropped!" });
          }}
          style={{
            width: "300px",
            height: "300px",
            backgroundColor: isHovering ? "blue" : "gray"
          }}
        >
          Drop Area
        </div>
        <div>{file ? file : "no file"}</div>
      </div>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by oliverodaa** [comment]
Interesting update: the snippet above works correctly if you move some code to an `afterEach()` block:

```js
context('App', () => {
  it('does stuff', () => {
    cy.visit('https://o10k74xq06.codesandbox.io/');

    cy.fixture('huge.json').then(content => {
      const base = Buffer.from(JSON.stringify(content)).toString('base64');

      cy.get('#drag-drop-area').upload(base, 'huge.json', 'application/json');
    });
  });

  afterEach(() => {
      cy
        .get('div')
        .contains('File dropped!');
  });
});
```

**Comment by oliverodaa** [comment]
New update: seems like a race condition issue. The solution is to make the `upload` command `then`-able.

```js
Cypress.Commands.add(
  'upload',
  { prevSubject: 'element' },
  (subject, file, fileName, mimeType) => {
    return cy.window().then(window => {
      return Cypress.Blob.base64StringToBlob(file, mimeType).then(blob => {
        const testFile = new window.File([blob], fileName, { type: mimeType });
        cy.wrap(subject).trigger('drop', {
          dataTransfer: {
            files: [testFile],
            types: ['Files'],
          },
        });
        return new Cypress.Promise(resolve => resolve());
      });
    });
  }
);
```
Then the test can do stuff in a `then` block like so:

```js
context('App', () => {
  it('does stuff', () => {
    cy.visit('https://o10k74xq06.codesandbox.io/');

    cy.fixture('huge.json').then(content => {
      const base = Buffer.from(JSON.stringify(content)).toString('base64');

      cy
        .get('#drag-drop-area')
        .upload(file, 'huge.json', 'application/json')
        .then(() => {
          cy.get('div').contains('File dropped!');
        });
  });
});
```

**Comment by abramenal** [comment]
Hi @oliverodaa 
Thanks for the investigation!

It definitely might be a race condition since I've experienced the thing you mentioned some time ago. Cannot recall it right now, but will find that test case during this week for sure.
Your effort should definitely be recognized! If you can make a pull request with this tiny change I would be happy to add you to our contributors honor list 💪
We just need to make sure we do fix the issue instead of hiding the root cause. @lunxiao can test its case as well targeting this PR

**Comment by oliverodaa** [comment]
Hi @abramenal, here is the PR: https://github.com/abramenal/cypress-file-upload/pull/13
