### ISSUE TITLE
first run fail of upload

### ISSUE THREAD

**Issue by adventmedia** [abramenal/cypress-file-upload#123]
Problem with uploader (for React);

Here is the html:

```jsx
      <div style={{ display: 'none' }} data-cy="uppy-input">
        <div className="UppyForm" ref={uppyFormEl} />
      </div>

```
Rendered DOM looks like this:

```html
<div data-cy="uppy-input" style="display: none;">
  <div class="UppyForm">
    <div class="uppy-Root uppy-FileInput-container">
       <input class="uppy-FileInput-input" type="file" name="files[]" multiple="" accept="image/*" style="">
    </div>
  </div>
</div>
```

This is the test:

```js
    cy.fixture('images/bucephalus.jpg', 'base64', { timeout: 12000 }).then(
      fileContent => {
        cy.get('[data-cy=uppy-input] input', {
          timeout: 12000,
          force: true,
        }).upload(
          { fileContent, fileName: 'bucephalus.jpg', mimeType: 'image/jpeg' },
          { subjectType: 'input' }
        );
      }
    );
```
On first run, Cypress throws this:
![uppy timeout](https://user-images.githubusercontent.com/1529172/67896990-dc556a80-fb33-11e9-8e4f-795935295e77.jpg)

This always happens on first run of the spec - subsequent runs usually (not always) pass.

Cypress 3.4.1, 3.5; cypress-file-upload: 3.1.1, 3.4.0; React 16.8.1; MacOS 10.14.6; Chrome 78.0.3904.70

**Comment by abramenal** [comment]
Hi @adventmedia 
Thanks for submitting the issue!

First, you likely don't need any timeout on `cy.fixture`
Then, if you use `force` option on `cy.get` then likely you need it on `.upload` command as well.

Please update your code snippet with mentioned changes and check if that works.

**Comment by adventmedia** [comment]
Unfortunately none of those suggestions help. In fact, following updates to cypress etc., it now fails every time.
I strongly suspect the issue has to do with the fact that we're using uppy (https://github.com/transloadit/uppy), the input element is created by uppy, it does not exist in the native DOM

**Comment by abramenal** [comment]
@adventmedia do you mean element is created inside shadow DOM? Or how it isn't exist in native DOM?
