### ISSUE TITLE
[Bug]Tests using upload are crashing on jenkins

### ISSUE THREAD

**Issue by ChandraPuvendhan** [abramenal/cypress-file-upload#126]

**Comment by abramenal** [comment]
Hi @ChandraPuvendhan 
Please submit any details about that issue. Until that I close the issue

**Comment by ChandraPuvendhan** [comment]
Current behavior:

[image: image]
<https://user-images.githubusercontent.com/41319515/69211946-c90f4b00-0b85-11ea-93a2-bdc925fbf163.png>
File open dialog box pops up when cypress file upload plugin is used
[image: image]
<https://user-images.githubusercontent.com/41319515/69211964-d7f5fd80-0b85-11ea-94ea-d6138162ae36.png>
Desired behavior:

File open dialog box should not pop up when cypress file upload plugin is
used
Steps to reproduce: (app code and test code)

cy.fixture('OutputContract.txt').then((updatedcontractexcel) => {
cy.log(updatedcontractexcel)

        cy.readFile(updatedcontractexcel, 'base64').then(fileContent => {

            cy.get('input[type="file"]').upload({
                fileContent,
                fileName: updatedcontractexcel,
                mimeType:
"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                encoding: "base64"
            },
                {
                    uploadType: 'input'
                }
            )
            cy.xpath("/html/body/div[4]/div/div/div[2]/div/div[1]/div[3]/div[2]/input").type('DocumentationLink'
+ timestampval.getTimestamp())
            cy.xpath("/html/body/div[4]/div/div/div[2]/div/div[1]/div[3]/div[4]/input").type('Comments'
+ timestampval.getTimestamp())

            cy.xpath("//div[@class='btn-group btn-group-sm
pull-right']//button[@class='btn btn-primary
ng-binding'][contains(text(),'Upload')]").click({ force: true })
        })
    })
