### ISSUE TITLE
[Bug]Tests using upload are crashing on jenkins

### ISSUE THREAD

**Issue by ChandraPuvendhan** [abramenal/cypress-file-upload#128]
### Current behavior:

![image](https://user-images.githubusercontent.com/41319515/69211946-c90f4b00-0b85-11ea-93a2-bdc925fbf163.png)
File open dialog box pops up when cypress file upload plugin is used
![image](https://user-images.githubusercontent.com/41319515/69211964-d7f5fd80-0b85-11ea-94ea-d6138162ae36.png)

### Desired behavior:

File open dialog box should not pop up when cypress file upload plugin is used

### Steps to reproduce: (app code and test code)

cy.fixture('OutputContract.txt').then((updatedcontractexcel) => {
            cy.log(updatedcontractexcel)

            cy.readFile(updatedcontractexcel, 'base64').then(fileContent => {

                cy.get('input[type="file"]').upload({
                    fileContent,
                    fileName: updatedcontractexcel,
                    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    encoding: "base64"
                },
                    {
                        uploadType: 'input'
                    }
                )
                cy.xpath("/html/body/div[4]/div/div/div[2]/div/div[1]/div[3]/div[2]/input").type('DocumentationLink' + timestampval.getTimestamp())
                cy.xpath("/html/body/div[4]/div/div/div[2]/div/div[1]/div[3]/div[4]/input").type('Comments' + timestampval.getTimestamp())

                cy.xpath("//div[@class='btn-group btn-group-sm pull-right']//button[@class='btn btn-primary ng-binding'][contains(text(),'Upload')]").click({ force: true })
            })
        })

**Comment by abramenal** [comment]
Hi @ChandraPuvendhan 
Thanks for submitting the issue.

Is it working on your local machine? Generally there's no reason for Cypress to open file upload dialog until you explicitly click on upload component (this is what you might do in the last line of your code).

Also the txt to base64 excel conversion looks weird, please also check excel-related code samples: https://github.com/abramenal/cypress-file-upload/issues/102

**Comment by ChandraPuvendhan** [comment]
yes it is working on my local machine and nothing explicitly opens locally. Only with Jenkins I face this issue. Please assist. I referred https://gitter.im/cypress-io/cypress for excel conversion

![image](https://user-images.githubusercontent.com/41319515/69514489-81b40080-0f71-11ea-9425-f9805c99e4b6.png)

**Comment by abramenal** [comment]
@ChandraPuvendhan 

I am not sure I can assist with jenkins crashes specifically. The only way I see here is to ask other users whether they have faced such issues (like @leorigon). I would also expect your logs to contain any messages related to fixture pick/upload failure.
