### ISSUE TITLE
[Bug] `upload` doesn't upload files

### ISSUE THREAD

**Issue by x-yuri** [abramenal/cypress-file-upload#129]
### Current behavior:

`upload` command attaches a file, not uploads anything.

### Desired behavior:

Rename to `attachFile` or something. And you can make the interface easier to read while you're at it:

```js
cy.get('input[type="file"]')
    .attachFile('upload.png', 'image/png');
```

compared to:

```js
const fileName = 'upload.png';
cy.fixture(fileName).then(fileContent => {
    cy.get('input[type="file"]')
        .upload({fileContent, fileName, mimeType: 'image/png'});
});
```

**Comment by abramenal** [comment]
Hi @x-yuri 
Originally I thought about using `cy.fixture` inside of the command, but then decided to start with smaller thing.
Right now all this seems to be a good suggestion for major v4 release.
However I would not call it a bug but rather an enhancement thing to consider.

Let's keep this issue opened until v4 release. Maybe I or someone else pick this up and code properly.
Thank you!

**Comment by abramenal** [comment]
@x-yuri finally got time to improve this.
Thanks!

@all-contributors add @x-yuri for ideas
