### ISSUE TITLE
[Feature] Upload file using the button instead of input or drag&drop

### ISSUE THREAD

**Issue by areshetilo230718** [abramenal/cypress-file-upload#132]
### Current behavior:

There is the possibility to upload the file in case the chosen selector is drag&drop or input, but now I faced with the case when the chosen selector is button. So when I point the SubjectType (button) in the code , the "invalid subjectType" error message is displayed after running the test. 

export function uploadReceipt() {
    const fileName = '593523b7eac85260172337.png';
    cy.fixture(fileName).then(fileContent => {
        cy.get('button[ngf-select="$ctrl.uploadFiles($file, $invalidFiles, item, $index)"]').click().upload(
            {fileContent, fileName, mimeType: 'image/png'},
            {subjectType: 'button'},
        );
    });
}

### Desired behavior:

How to upload the file clicking on the button

### Versions

Cypress package version: 3.5.0
macOS Mojave V10.14.6
Chrome 78

**Comment by abramenal** [comment]
Hi @areshetilo230718 
Thanks for submitting the issue!
The case sounds weird, but fixing this is quite easy and does not affect the whole system.
So I think it's reasonable to do this.

Will you be able to code it so we can review changes together?

**Comment by areshetilo230718** [comment]
Hi @abramenal 
The case really weird, but I face with it quite often 

>Will you be able to code it so we can review changes together?

Sorry, I didn`t understand 
the part of code I wrote in the issue description

**Comment by abramenal** [comment]
Sorry @areshetilo230718 I meant making the fix in the plugin's source code. Thought it might be interesting for you to make a contribution yourself 😈

**Comment by abramenal** [comment]
Release with `v3.5.2`

**Comment by abramenal** [comment]
@MaxChu23 I think you're using newer plugin version where the command signature has slightly changed.
I suggest to either set specific v3 version in package.json, or look through the new API docs to see what's changed.

**Comment by nikhilnayyar002** [comment]
@MaxChu23 may be you can do this to check if your custom button is working

```js
export function checkAttachButton(shouldWork = true) {
    let clicked = false
    function listner(e) {
        e.preventDefault()
        clicked = true
        // cleanup
        e.currentTarget.removeEventListener("click", listner)
    }

    // attach a temprary listner to detect onclick event on hidden file input
    cy.get(classNames.chatWindowUploadFileHiddenInput).should("exist")
    cy.$$(classNames.chatWindowUploadFileHiddenInput)[0].addEventListener("click", listner)

    // click attach file button
    cy.get(classNames.chatWindowUploadFileBtn).click().then(()=>{
        assert.equal(clicked, shouldWork, "Attachment button" + (shouldWork ? "is working" : "is not working"))
    })
}
```

Basically we check if button does have a code registered to click an input[type=file]
Set `shouldWork` to true when you want button to work. Set false when you do not want it to work (to test file upload disabled functionality).

**Comment by raja28april** [comment]
Still the issue persists

I tried to upload file using
**approach1:**
>  cy.get(('button[type="button"]').selectFile('file.docx');
 and got the below error message
cy.selectFile() can only be called on an <input type="file"> or a <label for="fileInput"> pointing to or containing one. Your subject is: <button name="button" type="button" data-source="attach">

I tried with the below code as well 
**approach2:**
> cy.get(('button[type="button"]').attachFile('file.docx');
**approach3:**
>  cy.fixture('file.docx').then((fileContent) => {
>         cy.get('button[type="button"]').attachFile({
>             fileContent,
>             fileName: 'file.docx',
>             mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
>         })
>     })


for approach 2 and 3 there isn't any error but the file is not getting attached
