### ISSUE TITLE
[Bug] How to upload to Angular's ngx-dropzone

### ISSUE THREAD

**Issue by thiagobrez** [abramenal/cypress-file-upload#133]
### Current behavior:

Hi!

I'm trying to use the provided examples to upload a file via drag n' drop to Angular's `ngx-dropzone`:

```javascript
    const fileName = 'import-contacts-short.csv';

    cy.fixture(fileName).then(fileContent => {
      cy.get('[data-testid="dropzone"]').upload(
        { fileContent, fileName, mimeType: 'text/csv' },
        { subjectType: 'drag-n-drop' },
      );
    });
```

But I'm facing the following error:

![image](https://user-images.githubusercontent.com/26878038/70460421-097f2c00-1a95-11ea-9a59-c5f414f50ae1.png)

This suggests that I should be passing a `FileList`, as `.item` is a property of this class, but I can't, since it is a readonly constructor. If `ngx-dropzone` is meant to be supported, is there any workaround to this?

Thanks in advance.

### Desired behavior:

`upload` should support sending files via a `FileList`

**Comment by abramenal** [comment]
Hi @thiagobrez 
Thanks for submitting the issue!

Seems it should work naturally..
Which element has this `data-testid="dropzone"` attribute?
Can you please specify `cypress` and `cypress-file-upload` versions?

Let's fix this and possibly make a recipe with that plugin.

**Comment by thiagobrez** [comment]
Hey @abramenal, thanks for the quick response!

The test id is on the dropzone itself:

```html
<ngx-dropzone (change)="onSelect($event)" [multiple]="false" accept=".csv" data-testid="dropzone">
      ...
</ngx-dropzone>
```

Package versions are as following:

```json
  "devDependencies": {
    "cypress": "^3.6.0",
    "cypress-file-upload": "^3.5.0"
  }
```
Also, I've set a breakpoint on the `drop` event and saw that the `dataTransfer` object looks different between `cypress-file-upload` run and actually dropping the file.

Real file drop:
![image](https://user-images.githubusercontent.com/26878038/70557867-73193c00-1b62-11ea-830d-c231f1e4310d.png)

`cypress-file-upload` drop:
![image](https://user-images.githubusercontent.com/26878038/70557978-b2e02380-1b62-11ea-86f9-8384840693f4.png)

**Comment by abramenal** [comment]
@thiagobrez okay, now I see the problem!
I recall my investigation about that API, as per MDN `FileList` object is read-only, however we can utilize `DataTransfer` API which uses it internally.

**Comment by abramenal** [comment]
@all-contributors add @thiagobrez for bug

**Comment by abramenal** [comment]
@thiagobrez can you please test this in v3.5.1?

**Comment by thiagobrez** [comment]
Wow, perfect! Just tested and it is working as intended.

@abramenal Thanks again for package and quick response.

**Comment by abramenal** [comment]
@thiagobrez thank you for the feedback and detailed investigation!
And welcome to the contributors list 🥂
