### ISSUE TITLE
[Bug] - Trying to upload a `video/mp4` with `binary` encoding fails

### ISSUE THREAD

**Issue by teophilus** [abramenal/cypress-file-upload#136]
### Current behavior:

![image](https://user-images.githubusercontent.com/1396018/70584532-7aa30a00-1b8f-11ea-94bc-a4909c7c5c91.png)

![image](https://user-images.githubusercontent.com/1396018/70584941-a377cf00-1b90-11ea-8f92-cb4f251fe7e7.png)

$ file -I test_asset_02.mp4
> test_asset_02.mp4: video/mp4; charset=binary

### Desired behavior:

Trying to upload a `video/mp4` with `binary` encoding fails, I used the same command for Jpegs and such and they work perfect.

### Steps to reproduce: (app code and test code)

Upload an video/mp4 with binary encoding

### Versions

Cypress: 3.5.0 , operating system: locally OSX but running against a production server (Unix), browser: Electron

**Comment by abramenal** [comment]
Hi @teophilus 

Thanks for submitting the issue!
Can you please provide the code snippet? It seems it should work, as binary is one of the supported encodings:
https://github.com/abramenal/cypress-file-upload/blob/master/src/constants.js#L29

**Comment by jackguoAtJogg** [comment]
I have same issue, here's my code snippet:
```
.fixture('sample_video.mp4')
            .then(fileContent => {
                cy.get('#upload-video').upload({
                    fileContent,
                    fileName: 'sample_video.mp4',
                    mimeType: 'video/mp4',
                    encoding: 'binary'
                })
            })
```

**Comment by jackguoAtJogg** [comment]
But I'm getting different error.
![image](https://user-images.githubusercontent.com/56273621/70958092-fb995000-202c-11ea-8c78-eb08442410f9.png)

**Comment by jackguoAtJogg** [comment]
I got it fixed by setting encoding to 'utf8'.
```
.fixture('bear.mp4')
            .then(fileContent => {
                cy.get('#upload-video').upload({
                    fileContent,
                    fileName: 'bear.mp4',
                    mimeType: 'video/mp4',
                    encoding: 'utf8'
                })
            })
```

**Comment by abramenal** [comment]
@jackguoAtJogg 
Thanks for this!

@all-contributors add @jackguoAtJogg for question

**Comment by abramenal** [comment]
Mentioned the workaround in 97e2f46d426bc57d1befc51072cea384161cba69

**Comment by jackguoAtJogg** [comment]
Wow~ is my honor to be part the contributor~ 😁

**Comment by inovramadani** [comment]
Hello, in my case where I used mp4box library to have a check on video metadata before sending a video, the above workaround does not work. It produces wrong video metadata. The below workaround works:
- set encoding to base64 in cy.fixture()
- set encoding in cypress-file-upload .attachFile to base64.

**Comment by jackguoAtJogg** [comment]
> I got it fixed by setting encoding to 'utf8'.
> 
> ```
> .fixture('bear.mp4')
>             .then(fileContent => {
>                 cy.get('#upload-video').upload({
>                     fileContent,
>                     fileName: 'bear.mp4',
>                     mimeType: 'video/mp4',
>                     encoding: 'utf8'
>                 })
>             })
> ```

The upload not longer work, all you need to do is to change from `upload` to `attachFile`.

**Comment by HindyB** [comment]
> Hello, in my case where I used mp4box library to have a check on video metadata before sending a video, the above workaround does not work. It produces wrong video metadata. The below workaround works:
> 
> * set encoding to base64 in cy.fixture()
> * set encoding in cypress-file-upload .attachFile to base64.

Hello, 
Thank you for this, however, I'm trying to upload large or small video files then accepted, in order to test the right error message. The following result is obtained:
![image](https://user-images.githubusercontent.com/55153633/120005902-03f70800-bfe1-11eb-962f-3fd10ba3fb2f.png)

**Comment by pmerwin** [comment]
> Hello, in my case where I used mp4box library to have a check on video metadata before sending a video, the above workaround does not work. It produces wrong video metadata. The below workaround works:
> 
> * set encoding to base64 in cy.fixture()
> * set encoding in cypress-file-upload .attachFile to base64.

for others this is what worked for me:

```
cy.fixture('vidtest.mp4', { encoding: 'base64' }).then((fileContent) => {
            cy.get('[data-testid="video-component-upload-dropzone-input"]').attachFile({
                fileContent,
                fileName: 'vidtest.mp4',
                mimeType: 'video/mp4',
                encoding: 'base64'
            });
        }); ```

**Comment by HindyB** [comment]
> > Hello, in my case where I used mp4box library to have a check on video metadata before sending a video, the above workaround does not work. It produces wrong video metadata. The below workaround works:
> > 
> > * set encoding to base64 in cy.fixture()
> > * set encoding in cypress-file-upload .attachFile to base64.
> 
> for others this is what worked for me:
> 
> ```
> cy.fixture('vidtest.mp4', { encoding: 'base64' }).then((fileContent) => {
>             cy.get('[data-testid="video-component-upload-dropzone-input"]').attachFile({
>                 fileContent,
>                 fileName: 'vidtest.mp4',
>                 mimeType: 'video/mp4',
>                 encoding: 'base64'
>             });
>         }); ```
> ```

This works great for me, excluding uploading large video files

**Comment by dgarofalo** [comment]
I'm not getting any errors when following the above, but I am however still seeing issue with the video encoding and the output is not playable by the browser. Any suggestions would be helpful.

Versions:
`
    "cypress-file-upload": "^5.0.7",
    "cypress": "8.0.0",
`

**Comment by Parth909** [comment]
> { encoding: 'base64' }

What do you mean by large. Approximately how much large
