### ISSUE TITLE
[File upload on shadow dom component]

### ISSUE THREAD

**Issue by dennismail4u** [abramenal/cypress-file-upload#137]
### Current behavior:
I have a shadow dom file upload component where I can browse or drag and drop json or csv files. I tried the code you mentioned here. But didnt work. Can someone help me?

### Desired behavior:
Should be able to drag and drop my files to shadow dom file upload component.

### Versions

3.4.0, Windowws 10, chrome/electron

Thanks,
Dennis

**Comment by abramenal** [comment]
Hi @dennismail4u 
Thanks for submitting the issue!
Have you tried this recipe? It should work well
https://github.com/abramenal/cypress-file-upload/tree/master/recipes/react-dropzone

**Comment by dennismail4u** [comment]
Hi Abramenal,
Yes I tried the same. I am getting error saying "encoding is not valid". Below is the code I am trying. I wanted to upload both .bz2 and CSV files. Can you please help what should do to fix this.

const fileName = "sample.csv.bz2";
cy.fixture('testFile.png', 'base64').then(fileContent => {
                    cy.document({log: false})
                        .shadowGet("file-upload")
                        .shadowFind("div")
                        .shadowEq(0)
                        .upload(
                           { fileContent, fileName, mimeType: 'application/x-bzip2' }, { subjectNature: 'shadow', 
                               subjectType: 'drag-n-drop'}, {force: true}
                           );
                 });
