### ISSUE TITLE
.xml upload

### ISSUE THREAD

**Issue by grivard** [abramenal/cypress-file-upload#139]
I have a need to upload both .csv and .xml files.  cypress-file-upload works great on .csv files, but I can't get it to work for .xml.  The error I'm getting is: "encoding" is not valid.  Please look into docs to find supported "encoding" values.

I looked at your list of encodings (https://github.com/abramenal/cypress-file-upload/blob/master/src/constants.js#L29) as well as Cypress's (https://docs.cypress.io/api/commands/fixture.html#Arguments) but I could not find one for .xml.  I tried them all anyway, but all result in the same error.

Are .xml files supported?  If not, do you have any plans to support them?

If they are supported and I'm just doing something wrong, here's my code

cy.fixture('file.xml').then(importfile => {  //using default encoding, but I've tried all supported
	cy.log(importfile) // this correctly logs the file's content for most encoding values
	cy.get('#selectfile').upload(
		{ 
			fileContent: importfile, 
			fileName: 'file.xml', 
			mimeType: 'text/xml'
		}
	)
})

Thanks!

**Comment by yonigibbs** [comment]
@grivard, in case it's of use to you, we have tests which upload XML files. We use `"utf-8"` as the value for the `encoding` parameter. The file itself is saved using UTF-8 encoding, which is the default encoding for XML files.  Hope this helps.

**Comment by grivard** [comment]
Yes, that helps a lot!  Import of .xml works for us now!  Thanks a lot for the help!
