### ISSUE TITLE
Cannot upload json file[Bug]

### ISSUE THREAD

**Issue by Adambs** [abramenal/cypress-file-upload#140]
### Current behavior:

Error: JSON content could not be parsed
    at JSON.parseWithDate (/****/node_modules/json.date-extensions/json.date-extensions.js:93:23)

![image](https://user-images.githubusercontent.com/13707440/71587523-ab3ee980-2b26-11ea-95cb-8f9733388e7d.png)

### Desired behavior:

I try to upload the json file

### Steps to reproduce: (app code and test code)

cy.fixture(fileName).then(fileContent => {

  cy.get('.hidden-upload').upload({ fileContent, fileName, mimeType: 'application/json'});
});

**Comment by abramenal** [comment]
Hi @Adambs 
JSON files are supported for sure, 
please check out existing recipe:
https://github.com/abramenal/cypress-file-upload/blob/master/recipes/react-html5-input/cypress/integration/mimeTypes.spec.js#L30
