### ISSUE TITLE
[Bug] File Upload on Shadow Dom throws Encoding is not valid. 

### ISSUE THREAD

**Issue by dennismail4u** [abramenal/cypress-file-upload#146]
### Current behavior:
Hi Abramenal,
I am getting error saying "encoding is not valid". Below is the code I am trying. I wanted to upload both .bz2 and CSV files. Can you please help what should do to fix this.

const fileName = "sample.csv.bz2";
cy.fixture('testFile.png', 'base64').then(fileContent => {
                    cy.document({log: false})
                        .shadowGet("file-upload")
                        .shadowFind("div")
                        .shadowEq(0)
                        .upload(
                           { fileContent, fileName, mimeType: 'application/x-bzip2' }, { subjectNature: 'shadow', 
                               subjectType: 'drag-n-drop'}, {force: true}
                           );
                 });

**Comment by abramenal** [comment]
Hi @dennismail4u 
Thanks for submitting the issue!

There's a file option called `encoding` which internally helps using proper function to process file contents. Normally it gets automatically assigned based on file extension, but `.bz2` is not the one supported by default. Thus, you need to specify it explicitly, so your code should look like:
```
.upload(
{ fileContent, fileName, mimeType: 'application/x-bzip2', encoding: 'utf-8' }, { subjectNature: 'shadow',
subjectType: 'drag-n-drop', force: true}
);
```

I am not completely sure whether utf8 will work, but think one of the supported encodings should work:
https://github.com/abramenal/cypress-file-upload/blob/master/src/constants.js#L29

PS: please note that I've moved `force: true` to second argument's properties as the command accepts only 2 objects as function parameters, not 3 as you've tried.

Let me know if something goes wrong,
Cheers 🥂

**Comment by dennismail4u** [comment]
Hi Abramenal,
I tried by passing different encoding values such as 'binary', 'utf8', etc. Now I am not getting any error, but the file is not getting uploaded to the component. Can you suggest some clue how should proceed? Should I try uploading into diff DOM element than the one i tried?

Dennis

**Comment by abramenal** [comment]
@dennismail4u if that is drag-n-drop component you should look for the element to which the drop event handler is attached to. If you're using some external component, it is likely its' root element.

**Comment by dennismail4u** [comment]
@abramenal I tried to drag and drop with different DOM elements, but didnt work. But I was able to upload the file using input type into one element. Thanks for all your help on this.. Cheers :)

Dennis
