### ISSUE TITLE
[Bug] Drag n Drop not working in headless Chrome with Cypress V3.8.2

### ISSUE THREAD

**Issue by pkell** [abramenal/cypress-file-upload#147]
### Current behavior:

When running cypress tests under headless Chrome, drag n drop upload does not work. Video playback shows nothing is triggered on the drop zone. The tests pass when run under headed chrome.

### Steps to reproduce:
1. Run a drag n drop upload test using the --headless --browser chrome flags

### Versions

Windows 10, Chrome 81 (canary), Cypress 3.8.2

**Comment by abramenal** [comment]
Hi @pkell 
Thanks for submitting the issue!

Will try to take a look on this later this week.

**Comment by pkell** [comment]
Seems like this still works with headless chrome under Cypress v3.8.3 if I revert cypress-file-upload to v3.5.0 instead of latest.

**Comment by abramenal** [comment]
Hi @pkell 
I've tested this on latest master and cannot reproduce the issue. Added the recipe to cover both visible and hidden drag-n-drops:
https://github.com/abramenal/cypress-file-upload/blob/master/recipes/react-dropzone/cypress/integration/dropzone.spec.js

I'm going to release a new version in the upcoming days so then you could test this with your setup. In the meantime you can try running the recipe locally.

Keeping this issue until the mentioned release.

**Comment by abramenal** [comment]
Hi @pkell 
Tested this in v4, it's working.
Please check out and feel free to reopen in case you spot something!

Cheers!
