### ISSUE TITLE
[Bug] InvalidStateError: Failed to set the 'value' property on 'HTMLInputElement'

### ISSUE THREAD

**Issue by jimpriest** [abramenal/cypress-file-upload#148]
### Current behavior:
I have a vanilla web form and I'm trying to upload a file (just getting started with Cypress)

I am getting an error when I submit form:

> InvalidStateError: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.

### Desired behavior:

Have the file uploaded with no error.

### Steps to reproduce: (app code and test code)

Using examples I've found on the web I have:

Form:
```
<form action="/?action=foo.save" method="post" enctype="multipart/form-data">
    <label>Attachment Name
      <input type="text" name="attachmentName" id="attachmentName" data-testid="attachmentName" value="" maxlength="255" required="true"/>
    </label>

    <label>Attachment File
      <input type="file" name="uploadfile" id="uploadFile" data-testid="uploadFile" value="" maxlength="255" required="true" />
    </label>
  
    <button type="submit" name="save" id="save" data-testid="btn_save_ext_attachment" >Save</button>
</form>
```

Spec:
```
  cy.fixture( po.attachmentfile ).then(fileContent => {
    cy.gettestid('uploadFile').upload({ 
      fileContent
      , fileName: 'test_file.txt'
      , mimeType: 'text/plain' 
    });
  });

  cy.gettestid('btn_save_ext_attachment').click()
```

This works!  The file is uploaded...  But my test fails with this message in Test Runner:

> InvalidStateError: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.

### Versions

Cypress 3.8.2
Chrome 79
Node 12.8.1

**Comment by abramenal** [comment]
Hi @jimpriest 
Thanks for submitting the issue!

Your example seems to be correct, let me check later this week if there's any changes in latest Chrome that does not allow to do this. More to come

**Comment by jimpriest** [comment]
I think this may be something weird on my end. :( 

I setup a vanilla PHP form on my personal site and was able to successfully upload a file there.  

At work we're using ColdFusion and even using a stripped down form I still get this InvalidStateError error.  Going to continue to simplify things and see if I can make it work.

Let me know if you find anything on your end :)
