### ISSUE TITLE
[Bug] force:true does not work for Dropzone drag-n-drop

### ISSUE THREAD

**Issue by allanslim** [abramenal/cypress-file-upload#150]
Hi Everyone,
How are you? I hope you are all doing fine! I am getting this error (see below) after implementing Dropzone drag-n-drop upload. I tried using  `force: true` parameter, but it only works for input and not for drag-n-drop. The way our upload functionality works, is that the `Dropzone` div disappears after it get's the file and a button ( labeled "Upload" ) needs to be clicked to upload the file.

```
CypressError: cy.trigger() failed because this element is detached from the DOM.

<div data-cy="dropzone">...</div>

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  > cy.trigger()

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element
```

Here's how I used the upload library:

```
        let fileName = 'test,txt'
        cy.fixture(fileName, 'base64').then(fileContent => {
            cy.get('[data-cy=dropzone]')
                .upload(
                    {fileContent, fileName, mimeType: 'text/plain', encoding: 'utf-8'},
                    {subjectType: 'drag-n-drop',  force: true},
                )
                .should(() => {
                    cy.log('here');
                    cy.get('[data-cy="uploadButton"]').click();
                });
        });```


Here are the versions:

cypress-file-upload: ^3.5.3
cypress: ^3.8.3
MacOS: 10.15.2

Thank you!

**Comment by allanslim** [comment]
I was thinking along the line of adding a `if (isManualEventTrigger({ window, force }))` check for DragDrop. Thanks.

**Comment by abramenal** [comment]
Hi @allanslim!

Thanks for submitting the issue!
Actually this gets a bit complicated as long as there's an `events` parameter which explicitly states which events to trigger manually.

So I think a proper way now to do it for drag-n-drop is:
```
cy.get('[data-cy=dropzone]')
   .upload(
    {fileContent, fileName, mimeType: 'text/plain', encoding: 'utf-8'},
    {subjectType: 'drag-n-drop',  force: true, events: ['dragenter', 'drop', 'dragleave', 'change'] },
 )
```

**Comment by abramenal** [comment]
@allanslim I've added a test case to describe how this should work with hidden drag-n-drop:

https://github.com/abramenal/cypress-file-upload/blob/master/recipes/react-dropzone/cypress/integration/dropzone.spec.js
