### ISSUE TITLE
[Feature] Upgrade to Cypress 4

### ISSUE THREAD

**Issue by warpech** [abramenal/cypress-file-upload#153]
### Current behavior:

This plugin requires Cypress 3.x.x according to https://github.com/abramenal/cypress-file-upload/blob/9df046cc78db802a0943d9dac82bbd60be029072/package.json#L45.

### Desired behavior:

I wish the plugin is updated to work with the current version of Cypress, which is 4.0.1.

Thanks for a great plugin! 👋

**Comment by abramenal** [comment]
Hi @warpech 
Thanks for submitting the issue!

I am really happy that the plugin went so widely used among the community 😃 
With regards to new version I expect a bunch of issues either related to v4 itself or cross-browser compatibility (like #154) 

So I would expect having proper tests and fixing all ongoing issues until the end of February.

Stay tuned! 🌟

**Comment by valscion** [comment]
For us, all of our tests, including the ones that used `cypress-file-upload` to upload an image to a form using https://www.dropzonejs.com/, worked flawlessly with Firefox and Cypress v4 :relaxed:

We merely ignore the warning generated by the peer dependency requirement of `cypress-file-upload` for now

**Comment by jimmyandrade** [comment]
Given I have `yarn` version ` version 1.21.1` and `cypress-file-upload` version 3.5.3
When I run `yarn install`
Then I find this:

```
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > cypress-file-upload@3.5.3" has incorrect peer dependency "cypress@^3.0.0".
[5/5] 🔨  Building fresh packages...

success Saved lockfile.
✨  Done in 21.57s.

Process finished with exit code 0
```

For now I'm ignoring the warning (like @valscion said) but it would be better if this warning does not appear.

**Comment by abramenal** [comment]
Hi @warpech @valscion @jimmyandrade,
it's now fixed with v4 release, please check out!

Cheers!
