### ISSUE TITLE
[Bug] Support Firefox (Cypress 4.0.1)

### ISSUE THREAD

**Issue by sandrina-p** [abramenal/cypress-file-upload#154]
### Current behavior:

I have a test to upload a file (image/png) and it's been working fine on Chrome with Cypress 3.x and the [new release 4.0](https://cypress.io/blog/2020/02/06/introducing-firefox-and-edge-support-in-cypress-4-0/9. But when I run it on Firefox (with Cypress 4.0.1) it doesn't work anymore.

- Firefox Developer Edition 73
![image](https://user-images.githubusercontent.com/14869087/74128991-6baff680-4bd6-11ea-91a0-98a1068902b5.png)

### Desired behavior:
- Chrome 79 (the test is passing on Cypress 3.x and Cypress 4.0.1
![image](https://user-images.githubusercontent.com/14869087/74129058-91d59680-4bd6-11ea-8862-e6ad8d19f9fc.png)

### Steps to reproduce: (app code and test code)

The HTML is like this:
```html

  <label>
    <img src="image.png" alt="">
    <span>Change avatar</span>
    <input type="file" name="picture" accept="image/*" placeholder="http://" data-test="avatar" class="sr-only">
  </label>
  <div>
      <i class="icon-check-circle"></i>
      <div data-test="avatarMsg" class="c-inner-text">Avatar updated!</div>
  </div>
```

The Cypress is the following:

```js
  it('user1 changes avatar and profile settings', () => {
    const profilePicture = 'imageTest.png' // at fixtures/imageTest

    cy.getByDT('settingsBtn').click()

    cy.fixture(profilePicture, 'base64').then(fileContent => {
      cy.get('[data-test="avatar"]').upload({ fileContent, fileName: profilePicture, mimeType: 'image/png' }, { subjectType: 'input' })
    })

    cy.getByDT('avatarMsg').should('contain', 'Avatar updated!')
  });
```

### Versions
- Cypress 3.5 (working on Chrome 79)
- Cypress 4.0.1 (not working on Firefox)
- Firefox Developer Edition 73
- Mac OS Mojave

**Comment by abramenal** [comment]
Hi @sandrina-p 
Thanks for submitting the issue!

Never tested v4 yet, so any contribution is appreciated.
I expect to have time fixing it later this week

**Comment by bbonevPIT** [comment]
I am having similar issue, Its working on chrome but not on firefox, its not failing it but its not working on firefox for sure.

**Comment by bbonevPIT** [comment]
I installed the latest changes from the plugin but it still doesnt upload the image in firefox, it doest on chrome though without problems as usual.

I dont get an error in firefox its just passing it but not uploaded, has anyone else have the same issue with latest version of cypress?

**Comment by abramenal** [comment]
Hi @bbonevPIT v4 is not yet released, expect it not later than Wednesday this week 🥂

**Comment by bbonevPIT** [comment]
@abramenal ah great, thank you very much. great job guys!

**Comment by dotwork** [comment]
My company has started using Cypress for our functional testing and we're loving it. We're hoping to replace our robot framework tests, but we need to have Firefox coverage. Any chance this fix will be coming in the next week or so?

**Comment by abramenal** [comment]
Hi all,
@sandrina-p @bbonevPIT @dotwork it's supported now with v4 release.
Please check out!

Cheers!

**Comment by dotwork** [comment]
Excellent, thank you!

**Comment by dotwork** [comment]
I have installed version 4.0.1, and am now getting the error `TypeError: cy.get(...).upload is not a function` on both Chrome and Firefox.

**Comment by dotwork** [comment]
To sanity check, I downgraded and re-ran tests on Chrome without any code changes and it worked fine.

**Comment by abramenal** [comment]
@dotwork the command itself was upgraded to simpler notation, please check out latest API guide 😄

**Comment by dotwork** [comment]
Got it, thank you! I do notice one side-effect seems to be more generic mimetypes. Where before I got:

- epub > application/epub+zip
- docx > application/vnd.openxmlformats-officedocument.wordprocessingml.document
- odt > application/zip to equal application/vnd.oasis.opendocument.text

now all 3 above just return `application/zip`. Is there a way to get the specific mimetype again?

**Comment by dotwork** [comment]
Also, nice improvement to the command! Much cleaner.

**Comment by dotwork** [comment]
I'm having a problem with the file upload. When uploading a valid docx file, it works on my test server if I do it manually, but when cypress does it, I get an error about it being corrupted. I've tried not passing an encoding, as well as using `base64` which is what was working on the previous version, and `binary` as well. 

Also, I am getting more generic mimetypes when I check the uploaded file. Where before I got:
epub > application/epub+zip
docx > application/vnd.openxmlformats-officedocument.wordprocessingml.document
odt > application/zip to equal application/vnd.oasis.opendocument.text
now all 3 above just return application/zip.

**Comment by dotwork** [comment]
Here is the docx file I am testing...
[valid_minimal.docx](https://github.com/abramenal/cypress-file-upload/files/4370372/valid_minimal.docx)

**Comment by abramenal** [comment]
@dotwork is this relevant only in Firefox? 
If not, let's move to a separate issue.

As for the mime type, I'll revert back the possibility to provide mime type manually, now there's auto-detection mechanism which relies on `mime` package.

**Comment by SonaliAvaya** [comment]
I know this is closed bug but still find the same issue on firefox browser 
Upload a file is not working on firefox but its working on chrome and electron.
its not giving any error but file is not uploading as well 
Using 
"cypress": "^4.7.0",
"cypress-file-upload": "^4.0.0"

**Comment by abramenal** [comment]
@SonaliAvaya can you please do the following:
- check your setup with latest plugin version (v4.0.7 as of now)
- if that is not working, please check out the usage examples in README or complete setups in recipes folder
-  if that is not working still, please create a new issue and describe more specifically your setup, issue so I can work on that


Right now in auto tests suite I execute tests against Firefox, Chrome and Electron, so there's high possibility that something is wrong with your code setup ;)
