### ISSUE TITLE
[Feature] Support SVG files

### ISSUE THREAD

**Issue by benowenssonos** [abramenal/cypress-file-upload#155]
### Current behavior:
It appears as though SVG files are not supported at this time. They are not included in the supported file extensions in https://github.com/abramenal/cypress-file-upload/blob/master/src/constants.js

### Desired behavior:

Support SVG files 😀

**Comment by abramenal** [comment]
Hi @benowenssonos 

Thanks for submitting the issue!

SVG is still supported by manually setting the file encoding (I omitted the rest):
```
/* ... */
cy
  .get('[data-cy="input"]')
  .upload({ fileContent, fileName, mimeType, encoding: 'utf8' });
```

Anyways that's a good change so releasing this soon. Stay tuned.

**Comment by abramenal** [comment]
@all-contributors add @benowenssonos for bug

**Comment by benowenssonos** [comment]
Thanks so much @abramenal. I will test this tomorrow.
