### ISSUE TITLE
[Bug] Upload with HTML file input does not work in Chrome > 73

### ISSUE THREAD

**Issue by narinepoghosyan** [abramenal/cypress-file-upload#156]
### Current behavior:
File upload does not gets triggered when using Chrome v73 and higher.

### Steps to reproduce: (app code and test code)
For file upload I am using  function like this

```
command.js
 Cypress.Commands.add('uploadFile', (fileName, fileType = ' ', selector) => {
    return cy.get(selector).then(subject => {
        cy.fixture(fileName, 'base64')
            .then(Cypress.Blob.base64StringToBlob)
            .then(blob => {
                const el = subject[0];
                const testFile = new File([blob], fileName, {
                    type: fileType
                });
                const dataTransfer = new DataTransfer();
                dataTransfer.items.add(testFile);
                el.files = dataTransfer.files;
            });
    });
 })
```
in my test file.
` cy.uploadFile(fileName, fileType, fileInput);`

It's working fine in chrome < 72

Now I am using chrome 80 and want to upload file with cypress-file-upload plugin.

-  First install plugin
npm install --save-dev cypress-file-uploa
my version:  cypress-file-upload@3.5.3

-  in commands.js I am import this line
import 'cypress-file-upload';

- In my test file 
```
        const fileName = 'GIF.gif';
        cy.fixture(fileName).then(fileContent => {
            cy.get('[type="file"]').upload({ fileContent, fileName, mimeType: 'image/gif' });
        });
```

**Actual result:** In cypress all steps shown, but in browser don't shown uploaded file.
See attached file
![Screenshot from 2020-02-13 17-06-59](https://user-images.githubusercontent.com/40800905/74439916-80b2b100-4e86-11ea-8aaa-ae662ff3b228.png)

**Comment by abramenal** [comment]
Hi @narinepoghosyan 
Thanks for submitting the issue!

I see you've posted also into the recipe issue. Please check out my latest comment there.
https://github.com/abramenal/cypress-file-upload/issues/34#issuecomment-587092333

**Comment by abramenal** [comment]
I've tested locally Chrome v79, 80 and both works as expected, auto detection mechanism under the hood enforces the change event triggering.

Anyways please try enforcing it, as I posted in mentioned commentt.

I also see possible issue in the specific element selection you drop image into. Can you please share more about your application setup? What lib do you use for input? Isn't it a drag-n-drop element? What exact element do you select when using cy.get?

**Comment by narinepoghosyan** [comment]
Tanks a lot for answer @abramenal.
I am trying the same code in other project and its working, but in my project I can't find any solution, Pls help me.
This is my html code

**Comment by narinepoghosyan** [comment]
This is my project the same code in chrome 70 version. There are working fine and my image is uploaded
![Screenshot from 2020-02-18 12-48-24](https://user-images.githubusercontent.com/40800905/74719331-3dbd5880-524d-11ea-92de-b970d2e6817c.png)

**Comment by narinepoghosyan** [comment]
And the same test in Chrome 80. This my image is not uploading.
![Screenshot from 2020-02-18 12-53-06](https://user-images.githubusercontent.com/40800905/74719648-dc49b980-524d-11ea-9507-65b6065fef23.png)
Please help my to find the problem

**Comment by benowenssonos** [comment]
@abramenal I am also running into this issue. It only appears when trying to upload an SVG (since you added this functionality yesterday).

**Comment by abramenal** [comment]
@narinepoghosyan can you please also try setting `subjectType: "input"`?
I think will have some time to debug this

**Comment by narinepoghosyan** [comment]
@abramenal  Thanks to answer.
Result  is the same. Chrome 80 - failed, Chrome 70  - pass
Code
```
        const fileName = 'PNG.png';
        cy.fixture(fileName, 'base64').then(fileContent => {
            cy.get('.t-file-uploader-input').upload(
               { fileContent, fileName, mimeType: 'image/png' },
              { subjectType: 'input', force: true },
         //      { subjectType: 'drag-n-drop'},
              );
       });
```
See attached  files
Chrome 80
![Screenshot from 2020-02-25 12-32-38](https://user-images.githubusercontent.com/40800905/75229540-8fc12980-57cb-11ea-9dd8-246926cdd4d2.png)
Chrome 70 
![Screenshot from 2020-02-25 12-36-08](https://user-images.githubusercontent.com/40800905/75229558-99e32800-57cb-11ea-9e12-29db764ba81a.png)

**Comment by artemisclyde** [comment]
Any news on this? I'm struggling with the same issue.

**Comment by abramenal** [comment]
Hey @narinepoghosyan @benowenssonos @artemisclyde @olibanjoli can someone provide a sample repo containing some code snippet and failing test? I cannot reproduce the issue locally using any of the tests for the recipes.

**Comment by narinepoghosyan** [comment]
Sorry @abramenal , I can't to send You. Our project is private and my manager don't let me to send. Sorry again.

**Comment by abramenal** [comment]
@narinepoghosyan it's fine. I actually meant that you could create a small project where you just use that dropzone component (is it open source one?) and test it with same code.

I expect the new release to come in the following 2 days, so if it's non-prio for you let's just wait a bit.

**Comment by narinepoghosyan** [comment]
@abramenal Okay I will wait and thanks a lot

**Comment by abramenal** [comment]
@narinepoghosyan @artemisclyde @benowenssonos finally got it done with v4.
Please check out and feel free to reopen if the issue persists.

Cheers!

**Comment by narinepoghosyan** [comment]
Thanks @abramenal, 	
I tried it, I still have the same issue

**Comment by flignac** [comment]
I have the same issue too and all page where i need to upload a file for a test is impossible with this issue.
