### ISSUE TITLE
xls and xlsx file support

### ISSUE THREAD

**Issue by tkeswa** [abramenal/cypress-file-upload#161]
I am getting error when I am trying to upload excel file (not csv) with encoding as uft-8

 [cypress-file-upload error]: "encoding" is not valid.
Please look into docs to find supported "encoding" values

**Comment by abramenal** [comment]
Hi @tkeswa 
Thanks for submitting the issue!

Right now encoding does not get decided automatically which is definitely a thing to improve.
In the meantime, you still can pass encoding explicitly, see: https://github.com/abramenal/cypress-file-upload/issues/102

**Comment by saschahofmann** [comment]
also see cypress-io/cypress#1594

**Comment by abramenal** [comment]
@saschahofmann thanks for your code snippet! Going to make this work out of the box in upcoming major release

**Comment by abramenal** [comment]
Hi @saschahofmann 
It should be supported now out of the box. Please check out v4!

Cheers!

**Comment by saschahofmann** [comment]
XLSX works like a charm. Not sure about XLS. Haven't dug deeper but there seems to be an issue.

Also the  docs link here: https://github.com/abramenal/cypress-file-upload/blob/master/src/constants.js for the encodings.
