### ISSUE TITLE
[Bug] Error when uploading empty file

### ISSUE THREAD

**Issue by asumaran** [abramenal/cypress-file-upload#162]
### Current behavior:

Cypress results:

```
1) File Upload Validation gives feedback when user uploads empty file:
   [cypress-file-upload error]: One or more field is invalid within given file(s).
Please look into docs to find supported "fileOrArray" values
    at http://localhost:3000/__cypress/tests?p=cypress/support/index.js-005:102:4029
    at Array.forEach (<anonymous>)
    at http://localhost:3000/__cypress/tests?p=cypress/support/index.js-005:102:3944
    at Context.<anonymous> (http://localhost:3000/__cypress/tests?p=cypress/support/index.js-005:102:4040)
```

Adding a white space in the file makes the test case not to throw an error.

### Desired behavior:

It should not throw any error

### Steps to reproduce: (app code and test code)

Upload an empty file

### Versions

cypress-file-upload@3.5.3
cypress@3.8.3

**Comment by asumaran** [comment]
Nevermind. I just read there's a `processingOpts.allowEmpty` option. Setting it to true does the trick. 

Closing the bug report. Sorry!.

**Comment by abramenal** [comment]
Hi @asumaran 
Thanks for submitting the issue!

You're right, this should work properly. Let me know if something goes wrong 😉

**Comment by asumaran** [comment]
@abramenal actually, the `allowEmpty` doesn't work quite properly. I left some comments here https://github.com/abramenal/cypress-file-upload/pull/119#pullrequestreview-364531524

**Comment by abramenal** [comment]
@asumaran that's a good point and it is already fixed in v4 which is coming not later than Wednesday.

Thanks anyway!

@all-contributors add @asumaran for bug
