### ISSUE TITLE
[Bug] Regression in v4

### ISSUE THREAD

**Issue by DamienCassou** [abramenal/cypress-file-upload#171]
### Current behavior:

In v3, I have the following code:

```js
cy.fixture(filename)
	.then(fileContent => {
		cy.getCy('upload').upload({
			fileContent,
			fileName: filename,
			mimeType: 'text/plain',
			encoding: 'utf8'
		});
	});
```

This correctly results in this data to be sent to my server:

```
------WebKitFormBoundaryKgicX5AvCMBvC3Qu
Content-Disposition: form-data; name="sieFile"; filename="sie/Demobolaget061231.sie"
Content-Type: text/plain
```

As you can see, `text/plain` is sent as content type.

With v4, the code is much simpler (thank you):

```js
cy.getCy('upload').attachFile({
	filePath: filename,
	encoding: 'utf8'
});
```

But I didn't find a way to specify the content type and this is what is sent to the server:

```
------WebKitFormBoundarykWS17JLeGqhGCuDh
Content-Disposition: form-data; name="sieFile"; filename="Demobolaget061231.sie"
Content-Type: null
```

The content type is now `null` instead of `text/plain`.

### Desired behavior:
I want `text/plain` as content type.

### Steps to reproduce: (app code and test code)

I don't have any reproducible code yet. Ask me if you really need one and I will more spend time on it.

### Versions

- Cypress: 4.2.0
- Browser: Chrome 82
- Operating system: Fedora 31

**Comment by DamienCassou** [comment]
Thank you very much. It works great now.

**Comment by abramenal** [comment]
Hey @DamienCassou 
Thanks for submitting the issue and verifying the fix! 🥇
