### ISSUE TITLE
[Bug] Uploading JSON file regression in v4

### ISSUE THREAD

**Issue by sanduteo95** [abramenal/cypress-file-upload#175]
### Current behavior:

In `cypress-file-upload` v3 I could do something like the following, to bypass a known `Cypress.fixture` issue documented here: https://github.com/cypress-io/cypress/issues/3138
```
cy.fixture(fileName)
	.then(fileContent => {
		cy.get(<selector>).upload({
			JSON.stringify(fileContent),
			fileName: fileName,
			mimeType: 'application/json',
			encoding: 'utf8'
		})
	})
```
Now in v4, since the `Cypress.fixture` line is built into the behaviour of the `attachFile` function (https://github.com/cypress-io/cypress/issues/3138), I am seeing that the uploaded file is formatted as `[Object object`].
### Desired behavior:
Instead of `[Object object]`, I'd expect to see the actual JSON object like I used to be able to by running `JSON.stringify` on the file returned by `Cypress.fixture`.

### Steps to reproduce: (app code and test code)
1. Try to attach a JSON file to a `Dropzone` component which reads the file:
```
cy.get(<selector>).attachFile(
          { filePath: <JSON file>, mimeType: 'application/json', encoding: 'utf-8' },
          { subjectType: 'drag-n-drop', force: true }
)
```
2. Read the file and see `[Object object]`
        
### Versions
`cypress@4.2.0`
`Mac OS X 10.7.4`
`Chrome 80`

**Comment by abramenal** [comment]
Hi @sanduteo95 
Thanks for submitting the issue!

Good catch, didn't know about that workaround.
Will let you know once this is fixed. If I'll get more issue with other fixture types I'll consider keeping original complex API as well.

**Comment by sanduteo95** [comment]
Hi @abramenal, do you have an ETA for this fix?

**Comment by jdcl32** [comment]
I have a similar flow to this one but using `wsdl` and `spss` files, I have submitted a PR that allow us to keep the workaround: https://github.com/abramenal/cypress-file-upload/pull/184

**Comment by abramenal** [comment]
A change of @jdcl32 is released in v4.0.5 so please take a look and let us know if something isn't working still.

**Comment by Anahkiasen** [comment]
@abramenal I just tried with 4.0.6 and I still get `[Object object]` unfortunately

**Comment by abramenal** [comment]
Just released the fix

**Comment by patroza** [comment]
@abramenal I use it like so:
```js
attachFile({
          fileContent: new Blob([jsonString], { type: "application/json" }), // a blob, because fileName has no .json
          fileName: "Some File", // no extension
          mimeType: "application/json",
          lastModified: new Date().getTime(),
        })
```

and couldn't for the life of me figure out why the behaviour is different when using:
```js
attachFile({
//          fileContent: new Blob([jsonString], { type: "application/json" }),
          fileContent: fileContent as any, // actual underlying object because attachFile automatically encodes it as JSON because fileName ends in .json
          fileName: "Some File.json", // <-- ends in .json
          mimeType: "application/json",
          lastModified: new Date().getTime(),
        })
```

Maybe if the fileContent is a blob, don't overwrite it when fileName ends in .json?

**Comment by abramenal** [comment]
@patroza well in your first example there is no way to determine file encoding automatically (as it is internally based on file extension). If you would like to pass whatever `fileContent` you should also specify `encoding` field, which determines the approach to build blob out of file content: https://github.com/abramenal/cypress-file-upload/blob/d553e202f3303cd201bff272cdadf45473bc86bc/lib/file/getFileBlobAsync.js#L6
