### ISSUE TITLE
cant upload image via firefoxe using Cypress

### ISSUE THREAD

**Issue by reallyusefulengine** [abramenal/cypress-file-upload#178]
I am trying to upload an image via cypress. The file upload seems to work with chrome but not with Firefox. The code is as follows:

    it.only('should prevent the user uploading file greater than 1mb', function() {
        cy.visit(locationSettingsPage, {failOnStatusCode: false})
        const fileName = 'heropanel.jpeg';
        cy.fixture('heropanel.jpeg', 'base64').then(fileContent => {
            cy.get('input#upload-logo').upload(
              { fileContent, fileName, mimeType: 'image/jpg' },
              { subjectType: 'input' },{force:true}
            );
            cy.wait(2000)
            cy.get('div.ms-MessageBar').should('have.text', 'Please upload a valid image file. Supported files are png and jpeg and must be under 1mb')
          });
    });

the html element is:

<input id="upload-logo" accept="image/png,image/jpeg" multiple="" type="file" style="display: none; max-width: 50px;">

am i doing something wrong here?

**Comment by abramenal** [comment]
Hi @reallyusefulengine 
Cross-browser support was introduced in v4, can you please check out latest API and let me know if that works in `v4.0.5`?
Thanks±
