### ISSUE TITLE
Duplicate definition of Chainable interface in index.d.ts

### ISSUE THREAD

**Issue by yonigibbs** [abramenal/cypress-file-upload#182]
The `Chainable` interface seems to be declared twice in `index.d.ts`: https://github.com/abramenal/cypress-file-upload/blob/master/types/index.d.ts#L16-L33. This is showing up as TypeScript compilation warning, both when viewing this file, and also if I declare my own `Chainable` interface and add methods to it. I think the cause is possibly the fact that the same type exists twice in `index.d.ts`, with different generic type parameters (so I don't think there's anything I can do in my own declaration of `Chainable` to fix this).

Additionally, there seems to be a slight mistake in the second declaration of the type, as in the type signature the generic type parameter is called `JQuery` but the `attachFile` method signature refers to `Subject`, which is the name of the type parameter in the first declaration.

![screenshot](https://user-images.githubusercontent.com/39593145/78359601-4b386300-75ad-11ea-8d63-1521fd5da35d.png)

**Comment by abramenal** [comment]
Hi, thanks for submitting the issue!

Right now I am not able to take a look into the issue properly.
In the meantime, I can suggest to check if the issue exist in v3 (previous major version):
https://github.com/abramenal/cypress-file-upload/tree/v3.5.3
Sorry about that. Not sure I can provide ETA on solving this issue in v4 since I am the only one contributor and maintainer. If you have ideas on fixing that, please feel free to open Pull Request and we can review it together.

Thanks for understanding.

**Comment by yonigibbs** [comment]
No worries at all @abramenal. This isn't a big deal, really. Shows up as a compilation problem in my IDE, but doesn't actually stop anything working/building. For the moment I've downgraded to 3.5.3 as you suggested on your readme.

In terms of a PR for this issue, from what I can see, that duplicate definition simply needs to be removed, in other words [these lines](https://github.com/abramenal/cypress-file-upload/blob/master/types/index.d.ts#L25-L33) can be deleted. They were introduced on Mar 22nd in [this commit](https://github.com/abramenal/cypress-file-upload/commit/8a86f899ff12b9dd3bdbdb8cbcb1ef79e18a43b2#diff-88bec6beae84369c0376b56b3bb88fe1), as part of adding es6+ targets support.

Do you happen to know if there's a specific reason this duplicate definition was added? Or was it just an oversight?  If there's no specific reason for it being there that you know of, I'll create a PR to remove those lines.

But like I say, totally no rush, so please don't feel any pressure to reply to this any time soon (or at all 😁).

**Comment by abramenal** [comment]
@yonigibbs that's a good point, I was just trying to fix the thing I am completely not aware of 🤣 
In `v4.0.5` there's a change of that, so it could work now
jfyi: https://github.com/abramenal/cypress-file-upload/issues/167#issuecomment-612105166

**Comment by yonigibbs** [comment]
The duplicate definition was removed in PR #187 and I can confirm this issue is now resolved in v4.0.6 (it was still a problem in v4.0.5).

Thanks again @jdcl32! 👍
