### ISSUE TITLE
xlsx file upload test fails due to dragleave trigger failure

### ISSUE THREAD

**Issue by Meenakshi2018** [abramenal/cypress-file-upload#188]
### Current behavior:

I'm trying to upload an xlsx file using drag-n-drop, the `dragenter` and `drop` triggers work fine, however, `dragleave` fails due to the error `element is detached from the DOM`.

Since, `drop` works the file gets uploaded, but the test fails due to the trigger failure.

```
CypressError: `cy.trigger()` failed because this element is detached from the DOM.

`<div ...</div>`

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  > `cy.trigger()`

This DOM element likely became detached somewhere between the previous and current command.
```

It doesn't work with cypress-file-upload 3.4.0, 3.5.3 versions for chrome, Firefox, electron, edge.

### Desired behavior:

The same thing works just fine with cypress-file-upload version 3.1.3, with cypress version 4.4.1 and chrome 81.

### Steps to reproduce: (app code and test code)
This is what I'm using to upload the file.

```
// Select the file to upload
    const fileName = 'Sheet.xlsx';
    const encoding = 'base64'

    cy.fixture(fileName, encoding).then(fileContent => {
        cy.get('._1o3oc').upload(
            { fileContent, fileName, mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', encoding },
            { subjectType: 'drag-n-drop' },
        );
    });
```

### Versions

Cypress 4.4.1
cypress-file-upload 3.5.3 or 3.4.0
chrome 81
firefox 73
MacOS 10.15.3

**Comment by abramenal** [comment]
Hi @Meenakshi2018 
Thanks for submitting the issue!
Nice catch, updated source code to handle that.
