### ISSUE TITLE
Upload image to filestack

### ISSUE THREAD

**Issue by LouiseReid** [abramenal/cypress-file-upload#189]
I'm trying to upload an image to a file stack drag and drop area. This is my code

```
      cy.fixture("example.png").then((image) => {
        cy.get(".fsp-drop-area").attachFile({
          image,
          encoding: "base64",
          mimeType: "image/jpeg",
        });
      });
```
but I get the error

```
[cypress-file-upload error]: "filePath" is not valid.
Please look into docs to find supported "filePath" values
```

This creates no errors but doesn't attach the file

```
      cy.get(".fsp-drop-area").attachFile({
        filePath: "exterior1.png",
        encoding: "base64",
        mimeType: "image/jpeg",
      });
```

Can someone explain what I'm doing wrong here?

Thanks

**Comment by abramenal** [comment]
Hi @LouiseReid 
Thanks for submitting the issue!
For your last code snippet – it looks correct with only one note – you're likely using drag-n-drop component instead of plain HTML5 file input. Thus, please use `subjectType` set to `'drag-n-drop'`, as provided in README docs and example recipes.

**Comment by BenAhlander** [comment]
I know this is closed...but if anyone lands here in the future, this worked for me

    cy.fixture("image.jpg").then((fileContent) => {
      cy.get("#fsp-fileUpload").attachFile({
        fileContent,
        fileName: "image",
        encoding: "base64",
        mimeType: "image/jpg",
      });
    });
