### ISSUE TITLE
Lost code intelliSense for jest after installed in a project with `@vue/cli-plugin-e2e-cypress` package

### ISSUE THREAD

**Issue by konni2020** [abramenal/cypress-file-upload#190]
### Current behavior:

I have a vue project generated by vue-cli, I installed cypress-file-upload, then the code intelliSense  for jest inside VSCode disappeared. If I uninstall `@vue/cli-plugin-e2e-cypress`, the  code IntelliSense will appear again.

One thing I found is that when I hover `expect ()`, it shows 
```
const expect: Chai.ExpectStatic
(val: any, message?: string) => Chai.Assertion
```
but after I removing `@vue/cli-plugin-e2e-cypress`,  hover `expect ()` will show
```
const expect: jest.Expect
<number>(actual: number) => jest.JestMatchersShape<jest.Matchers<void, number>, jest.Matchers<Promise<void>, number>>
```

### Desired behavior:
show correct code intelliSense 

### Steps to reproduce: (app code and test code)

[reproduce](https://github.com/konni2020/file-upload-test)

### Versions

VSCode 1.44.2
cypress-file-upload 4.0.6
@vue/cli-plugin-e2e-cypress 4.3.1

**Comment by abramenal** [comment]
Hi @konni2020 
Thanks for submitting the issue!
To be honest, I have no idea how this can affect IntelliSense stuff..
The only side thing except actual code that happens here is extending Cypress types with this code:
https://github.com/abramenal/cypress-file-upload/blob/master/types/index.d.ts
but still I am not sure this can affect IntelliSense.

**Comment by konni2020** [comment]
Hi @abramenal , thanks for taking the time to reply.
I'm sorry that the reason may not because this package, this [answer](https://stackoverflow.com/a/61838153) solved my issue.
