### ISSUE TITLE
MP3 Upload is not working

### ISSUE THREAD

**Issue by jessielaf** [abramenal/cypress-file-upload#191]
### Current behavior:

The file is not processed correctly resulting in the uploaded file not being the same as the original

### Desired behavior:

The file is uploaded with the right encoded data. I have a bell.mp3 and I added it to `cypress/fixtures`. Next up I installed `cypress-file-upload` version `4.0.4` and passed the fixture path. Looking like this:
```
cy.get('#file')
.attachFile('bell.mp3')
```

I also tried version `3.5.3` :
```
.fixture('bell.mp3')
.then(fileContent => {
    console.log('audo/mpeg')
    cy.get('#file').upload({ fileContent, fileName: 'bell.mp3', mimeType: 'audio/mpeg', encoding: 'utf8' })
})
```

But both of these will fail when the backend processes them. But when I upload the same file manually it does not fail.

### Versions

Cypress: 4.1 and 4.5
Chrome:  81.0.4044.129
OS: Windows 10

**Comment by abramenal** [comment]
Hi @jessielaf 
Thanks for submitting the issue!

I think for the audio files you need to use `encoding: 'binary'` explicitly? Can you please try this out? If it'll work, I'll update plugin internals to support that out of the box.

**Comment by jessielaf** [comment]
Yes you are right! Changing the encoding to binary worked. Thanks!
