### ISSUE TITLE
Cypress:Not able to upload a PDF file whose type is "text" and the attachment button is of tag img

### ISSUE THREAD

**Issue by AkramPasha** [abramenal/cypress-file-upload#197]
Hi,

I am trying to upload a pdf file using cypress-file-upload. where the HTML code is of not type 'file' it's 'text'

i have tried with following code for uploading the pdf file .

cy.get("input[placeholder='No Files selected']").invoke('attr', 'type', 'file')
 const fileName = "sample.pdf"   // pdf is saved under fixture folder
 cy.fixture(fileName).then(fileContent => {
   cy.get('[type="file"]').eq(1).upload({ fileContent, fileName, mimeType: 'application/pdf' });
 })

it does not give any error but also it does not upload anything.

![image](https://user-images.githubusercontent.com/17572477/82284931-d5028b00-99b7-11ea-8566-8020b4147a7d.png)

The HTML code for the following image is
![image](https://user-images.githubusercontent.com/17572477/82285014-04b19300-99b8-11ea-9b50-4e0c91a0b46f.png)

Thanks

**Comment by abramenal** [comment]
Hi @AkramPasha 
Thanks for submitting the issue.
I do not see how exactly you want to upload a file into text-based input – it should be originally file input so the browser will handle file contents properly.

Please check out this [html5 input recipe](https://github.com/abramenal/cypress-file-upload/tree/master/recipes/react-html5-input), that should help I think.

Feel free to re-open in case of any further issues.
