### ISSUE TITLE
[Feature] Multiple Files Support

### ISSUE THREAD

**Issue by kmui2** [abramenal/cypress-file-upload#20]
### Current behavior:
`upload` takes only a single file at a time.
https://github.com/abramenal/cypress-file-upload/blob/master/README.md#api

### Desired behavior:
`upload` can take multiple files at a time.

### Versions
Chrome Version 72.0.3626.121

    "cypress-file-upload": "2.0.0",
    "cypress": "3.1.5",

**Comment by abramenal** [comment]
Hi @kmui2 
Thank for contributing!

That sounds good! Need to think how to make the API convenient for both cases (single/multi).. hopefully this week will take a look and open a PR so we can review it together.

In the meantime it will be wonderful if you have some spare time and can take a look on it as well. You'll appear in the list of our dear contributors 😈

**Comment by kmui2** [comment]
@abramenal sounds good. I'll take a look too.
