### ISSUE TITLE
Cypress:Not able to upload a PDF file whose type is "text" and the attachment button is of tag img

### ISSUE THREAD

**Issue by AkramPasha** [abramenal/cypress-file-upload#201]
Hi @AkramPasha 
Thanks for submitting the issue.
I do not see how exactly you want to upload a file into text-based input – it should be originally file input so the browser will handle file contents properly.

Please check out this [html5 input recipe](https://github.com/abramenal/cypress-file-upload/tree/master/recipes/react-html5-input), that should help I think.

Feel free to re-open in case of any further issues.

_Originally posted by @abramenal in https://github.com/abramenal/cypress-file-upload/issues/197#issuecomment-633569302_

**Comment by AkramPasha** [comment]
Hi @abramenal,

Thank you for the reply.

but in my case i need to attach a pdf file.

![image](https://user-images.githubusercontent.com/17572477/82863867-d9dbb780-9f40-11ea-
9439-420ea2f72014.png)

in which the attachment button is of image tag not "input" tag. 
under the image tag there is no type attribute present

please find the below html code for attachment image.

<img src="/static/media/attach-file-24-px.63367ef2.svg" alt="upload file" class="jss264" css="1">


even i tried with following code to upload different type of file to check if that could happen 

 cy.get("[type=text]").attachFile({
        filePath: "sample.png",
        encoding: "base64",
        mimeType: "image/jpeg",
      });

did not get any error nor file is uploaded. 

Thanks in advance

**Comment by abramenal** [comment]
Hi @AkramPasha 
I get your setup. You should use either a valid HTML5 file input control or a 3rd-party component that handles file attach events internally.

That means this clip image you're referencing is not an actual element file will be attached to (even if you click there). I suggest checking what event handlers do you have in the application (likely it will be something like onchange/ondrop event). After you find this element, consider its selector for `cy.get().attachFile` and the rest should work good.

**Comment by AkramPasha** [comment]
Hi @abramenal ,

On clicking the image element is the one that will open the window pop-up for uploading the file.

if i select cy.get('[alt="upload file"]').attachFile().

**Comment by abramenal** [comment]
@AkramPasha like I said, clicking on image element does not mean it will be the destination of actual file attach
