### ISSUE TITLE
[Feature] Update the readme with instructions on how to add the attachFile command to typescript intellisense

### ISSUE THREAD

**Issue by UncleGus** [abramenal/cypress-file-upload#202]
### Current behavior:

When using the `.attachFile()` command, intellisense doesn't recognise it and underlines it red.

### Desired behavior:

Intellisense should recognise the command. This can be achieved by adding the command to `index.d.ts` in the `cypress/support` folder. More details in the Cypess custom commands documentation.

### Versions

N/A

**Comment by MCFreddie777** [comment]
Would help a lot.

**Comment by abramenal** [comment]
Hi @UncleGus @MCFreddie777 did you have a chance to check https://github.com/abramenal/cypress-file-upload/issues/167

`index.d.ts` is currently defined, but for some reason multiple users experience this issue. I'm not sure how exactly it should be fixed

**Comment by peterkrieg** [comment]
@abramenal   I just posted (https://github.com/abramenal/cypress-file-upload/issues/167#issuecomment-689672324)   in that issue (which I think can be closed if the solution works for people).  

I'd be happy to make a small PR outlining how to add the `types` to the `tsconfig.json`.  I'm thinking it could be a small blurb similar to how `cypress-testing-library` does it here:  https://github.com/testing-library/cypress-testing-library#with-typescript

Let me know what you think!

**Comment by abramenal** [comment]
Hi @peterkrieg 
Thanks for this solution! While waiting for someone else's feedback we can work on the PR.
Example that you mentioned is perfect – we can copy both `With TypeScript` and `Intellisense for JavaScript with VS Code` sections and put it between `Installation` and `Usage` too 👍

**Comment by MCFreddie777** [comment]
Update:
I tried multiple solutions but only one worked.

Previously I used  typeRoots in my project, so I tried to add it there:

```typescript
// /cypress/tsconfig.json
  "typeRoots": [
            "../node_modules/@types",
            "../node_modules/cypress/types",
            "../types",
            "../node_modules/cypress-file-upload"
        ]
```

Using this solution, my IDE (WebStorm) stopped complaining about not existing property, but when I ran the tests, I started getting errors such as `Cannot find type definition file for 'dist'` or `'node_modules'`.

Maybe its worth to mention that I'm running cypress@4.12.1 but without out-of-the-box typescript, still using `@cypress/webpack-preprocessor` to transpile typescript into js.

Well, I started trying more solutions as adding "../node_modules/cypress-file-upload/types" into the `typeRoots`, not working.
Tried adding `/// <reference types="Cypress" />` to the beginning of file where I am using the `attachFile` function with no luck.

The only solution that worked is:

```typescript
// /cypress/tsconfig.json
  "types": ["cypress", "cypress-file-upload"],
   "typeRoots": [
         "../node_modules/@types",
         "../types"
   ]
```

You can use both `typeRoots` and `types` in your `cypress/tsconfig.json` file.

**Comment by andrico1234** [comment]
> The only solution that worked is:
> 
> // /cypress/tsconfig.json
>   "types": ["cypress", "cypress-file-upload"],
>    "typeRoots": [
>          "../node_modules/@types",
>          "../types"
>    ]
> You can use both typeRoots and types in your cypress/tsconfig.json file.
> 
> 

This worked for me straight away, I'm surprised that this is not documented in the README.

**Comment by abramenal** [comment]
I think README indeed lacks of clarity on using command with TS, might be a good improvement for upcoming v5 release

**Comment by andrico1234** [comment]
I whipped up a super quick MR to include @MCFreddie777 's .tsconfig changes to the README, you can find it here: https://github.com/abramenal/cypress-file-upload/pull/246
