### ISSUE TITLE
File lastModified and lastModifiedDate properties are modified

### ISSUE THREAD

**Issue by tabcat** [abramenal/cypress-file-upload#208]
We are using cypress-file-upload to upload .jpg images. The files being uploaded are having their modified dates changed to the current date, it's important for us that this doesn't happen. Is there anyway to do this?

**Comment by josephzidell** [comment]
@tabcat Does this behavior exhibit itself when you upload manually, outside of Cypress?

**Comment by tabcat** [comment]
Uploading files through the app keeps the files original modification date. app in question: https://github.com/cypsela/sailplane-web

We changed the tests to not check the upload date so they would pass, which has been fine.
