### ISSUE TITLE
[Bug] in README.md `fixtures` -> `fixture`

### ISSUE THREAD

**Issue by Ebazhanov** [abramenal/cypress-file-upload#212]
### Current behavior:

       Inside [README.md](https://github.com/abramenal/cypress-file-upload/blob/master/README.md) file
      for two blocks we have incorrect name of `fixtures`

![image](https://user-images.githubusercontent.com/13170022/89898251-ab38b900-dbe0-11ea-9e38-3f30bf317dab.png)

### Desired behavior:

       To match requirements we have to use `fixture` instead of `fixtures`

![image](https://user-images.githubusercontent.com/13170022/89898646-5a759000-dbe1-11ea-9db2-3359bc5b9148.png)

### Steps to reproduce: (app code and test code)

     Use `fixtures` instead of `fixture`

### Versions

    "cypress-file-upload": "^4.0.7", / macOS / Chrome

### FYI 

    Pull request is read y to go [https://github.com/abramenal/cypress-file-upload/pull/211](https://github.com/abramenal/cypress-file-upload/pull/211)

**Comment by josephzidell** [comment]
Merged with #211
