### ISSUE TITLE
[Bug] Return type of Cypress.Blob changed from Promise to Blob in Cypress 5.0

### ISSUE THREAD

**Issue by caitcif** [abramenal/cypress-file-upload#217]
### Current behavior:

base64StringToBlob() no longer returns a Promise. Update the use of base64StringToBlob() to expect a returned Blob.Learn more

### Versions

Cypress 5.0

**Comment by anas-qa** [comment]
@caitcif duplicated with [#214](https://github.com/abramenal/cypress-file-upload/issues/214)

**Comment by josephzidell** [comment]
Closing as duplicate of #214
