### ISSUE TITLE
[Feature] Upload files out of /cypress/fixtures folder

### ISSUE THREAD

**Issue by MCFreddie777** [abramenal/cypress-file-upload#232]
### Current behavior:

```typescript
cy.get(this.fileInput).attachFile('/cypress/auth/mysql/mysql.json');
cy.get(this.fileInput).attachFile({fileName: 'mysql.json', filePath: '/cypress/auth/mysql/mysql.json'});
```

both result in 

```
A fixture file could not be found at any of the following paths:
> cypress/fixtures/cypress/auth/mysql/mysql.json
```

### Desired behavior:

Seems like the package is using `cy.fixture` instead of `cy.readFile` which appends `cypress/fixtures` by default, therefore its impossible to upload file elsewhere than this folder.

### Versions

Cypress: 4.12.1
Chrome: 85
OS: macOS 10.15 Catalina

**Comment by abhidp** [comment]
@MCFreddie777  Until this bug/feature is fixed, you can use the the `readFile` option as a workaround

```javascript
const filePath = 'cypress/downloads/example-bulk.csv'

cy.readFile(this.fileInput, 'binary')
  .then(Cypress.Blob.binaryStringToBlob)
  .then((fileContent) => {
    cy.get(this.fileInput).attachFile({
      filePath,
      fileContent
    })
  })
```
