### ISSUE TITLE
Unable to Upload Photos

### ISSUE THREAD

**Issue by akashtippa123** [abramenal/cypress-file-upload#233]
i tried to upload photos with this code

it('upload', function() { 
const yourFixturePath = 'cypress\fixtures\hd4.jpg';
 cy.get('.upload-button').attachFile(yourFixturePath);
}

it is not working with the above code, I tried an alternative way

cy.fixture('hd4').then((fileContent) => {
            cy.get('.upload-button').attachFile({
               fileContent: fileContent.toString(),
                fileName: 'hd4',
              mimeType: 'image/jpg'
            })
         })

if I try this above code, but the file is present in the cypress\fixtures\hd4.jpg I received this error 
please advise if anything wrong
![tile](https://user-images.githubusercontent.com/61974824/93417753-67635e80-f8c6-11ea-99b3-9bb747a9048b.png)

**Comment by Buthrakaur** [comment]
@akashtippa123 did you try to use the path without `cypress/fixtures` prefix? I think cypress automatically uses this path so you should provide just file name:

```
it('upload', function() {
  const yourFixturePath = 'hd4.jpg';
  cy.get('.upload-button').attachFile(yourFixturePath);
}
```

**Comment by akashtippa123** [comment]
yes I tried without the cypress/fixtures prefix, it is not working

**Comment by mariuspatrick** [comment]
I also have the same problem, only it's not giving me any errors. Does anyone have a fix for this?
Two weeks when I tried it, it was working.

**Comment by abramenal** [comment]
It accepts the filename of a file placed in fixtures folder that you want to upload.
So in case you have your `test.png` file put into `cypress/fixtures`, what you should provide into the command is just `test.png`.

**Comment by mariuspatrick** [comment]
I added the .jpg in the fixtures folder. Then I assign it to a const in my test file, after which I call the .attachFile(variableName) 

For some reason, it's not adding the file to the website

**Comment by abramenal** [comment]
@mariuspatrick is there any error log in console or cypress ui?

**Comment by mariuspatrick** [comment]
I am using the latest file-uploader version, 4.1.1

There is no error in the cypress ui. The test passes as long as I don't make any assertions to check whether the image is on page, which is strange

**Comment by mariuspatrick** [comment]
The problem was I was using a cypress recorder and it was selecting the button div, but I needed the input field to upload the file. I used inspect element to find the input field, I selected it and it worked.

**Comment by akashtippa123** [comment]
I also inspected input field, and trying to upload image it's not uploaded
for me, I didn't given any error

**Comment by akashtippa123** [comment]
Can you tell me in detail how it works for you

**Comment by akashtippa123** [comment]
@mariuspatrick  please help me how did you resolve this issue, I am also trying to resolve this from long day

**Comment by mariuspatrick** [comment]
I will try to explain this in detail, not sure if it will help solve your issue as well

First, I inspected the button element using inspect element in chrome dev tools. My button was inside a div, composed of 2 other elements. One of them was another div and the 2nd element was the actual input data element. I just had to use the 2nd element's selector, which was the input data element, and then it worked.

**Comment by akashtippa123** [comment]
is your input data element is disabled or enabled?

**Comment by MohmedEmad** [comment]
@akashtippa123 it's fixed with me by selecting the right input selector from the page, that is it

Thanks @mariuspatrick for your last comment

**Comment by debbyzang** [comment]
I try to upload files, but it doesn't work. I tried three ways, none is work for me . And I attach the expect result and the actual result

[](url)
<img width="658" alt="Snipaste_2020-12-28_17-24-00" src="https://user-images.githubusercontent.com/21197863/103204117-8ba4f180-4931-11eb-9761-60dd40ef5007.png">
<img width="617" alt="Snipaste_2020-12-28_17-23-19" src="https://user-images.githubusercontent.com/21197863/103204120-8d6eb500-4931-11eb-9655-79ad6d1e368b.png">


"cypress": "^6.2.0"
chrome:87.0.4280.88（正式版本） （64 位）

**Comment by abramenal** [comment]
Don't think this is relevant anymore. Feel free to reopen if you still experience this.
