### ISSUE TITLE
[Bug] Regression: Multiple files upload is no more available since 4.0.0

### ISSUE THREAD

**Issue by Aurangseb** [abramenal/cypress-file-upload#234]
### Current behavior:

Single file upload with attachFile(). In previous versions upload / uploadFiles was available for multiple file upload

### Desired behavior:

provide attachFiles() in order to be able to migrate code

**Comment by karansaini1** [comment]
When this functionality of uploading multiple files will be added?

**Comment by abramenal** [comment]
It's currently pending for this PR: https://github.com/abramenal/cypress-file-upload/pull/227
Personally I'm overloaded with job stuff, so would appreciate if someone can also dive into that PR and ensure the implementation passes all existing tests. After that we're free to release it

**Comment by abramenal** [comment]
Released with `v4.2.0`
