### ISSUE TITLE
[Bug]Upload image fail

### ISSUE THREAD

**Issue by mingyixu** [abramenal/cypress-file-upload#244]
### Current behavior:
I'm trying to upload an image to a file. This is my code
cy.get('#pic').attachFile({ filePath: 'abc', mimeType: 'image/jpg', encoding: 'base64' }, { subjectType: 'drag-n-drop' });

on mac is success, but cann't upload on linux. its must use : 
        cy.fixture("abc.jpg", 'binary')
            .then(Cypress.Blob.binaryStringToBlob)
            .then((fileContent) => {
                cy.get('#pic').attachFile({ fileContent, fileName: 'abc.jpg', mimeType: 'image/jpg', encoding: 'utf-8' });
            })
this method  not nice.

**Comment by abramenal** [comment]
Hi @mingyixu
Thanks for submitting the issue!
The two code snippets you mention use different encodings.
I think the correct one is `binary` which should automatically be recognized by the tool.
Here are things you can try:

```javascript
cy.get('#pic').attachFile('abc.jpg', { subjectType: 'drag-n-drop' });

// OR
cy.get('#pic').attachFile({ filePath: 'abc.jpg', mimeType: 'image/jpg', encoding: 'binary' }, { subjectType: 'drag-n-drop' });
```
