### ISSUE TITLE
[Bug] Need to specify encoding: "base64" for `.png` and `.jpg` images on cypress-file-upload version 5.0.2

### ISSUE THREAD

**Issue by inovramadani** [abramenal/cypress-file-upload#275]
### Current behavior:
Need to explicitly add encoding property to upload image properly. Below is part of my test code:

```javascript
export const sendImageMessage = (fileName, mimeType) => {
  cy.fixture(`pictures/${fileName}`)
    .then(fileContent => {
      cy.get('input#image-upload[type=file]')
        .attachFile(
          { fileContent, fileName, mimeType, encoding: 'base64' }, // need to explicitly add encoding property here to upload image properly
          { subjectType: 'input' }
        )
    })
}
```

Without adding encoding, the image is broken. The file input change handler will upload the image into s3 in my app functionality. If I try to download from s3 url from the upload callback, it will be showing as `It looks like we don't support this file format`. And the s3 url will be shown instead of the image on my app.

### Desired behavior:

Should be able to upload image smoothly without explicitly add encoding property. It worked fine when I used cypress-file-upload version 3.2.0. But after upgrading to 5.0.2 I need to do the above workaround.

**Comment by abramenal** [comment]
Not an issue, since png/jpg/jpeg/gif/etc file extensions are being resolved into `base64` file encodings. If your filename does not have extension (or have a different one), you have to specify encoding explicitly.
