### ISSUE TITLE
[Bug] Ngx-dropzone duplicated events

### ISSUE THREAD

**Issue by MikeDabrowski** [abramenal/cypress-file-upload#291]
### Current behavior:

When using this plugin to upload files onto ngx-dropzone (angular) the `changes` output fires twice.
This happens when using subject 'drag-n-drop'. When using 'input' output fires once but the event that it is passed is of wrong type (CustomEvent). Current workaround would be to modify my app to handle that CustomEvent structure too, or to debounce that event.

### Desired behavior:

It should only fire once.

### Steps to reproduce: (app code and test code)

I'm pasting the most relevant pieces. If anything else is necessary please ask for it in the comment.
When cypress executes this step, files are 'dropped' twice, and I got duplications all over the app.

```html
<ngx-dropzone (change)="handleFileInput($event)" >
```

```typescript
handleFileInput(stuff: NgxDropzoneChangeEvent) {
    console.log('handleInput', stuff); // fires twice
    //... handle files somehow ...
  }
```

```typescript
const files = [{
     filePath: `pdfs/valid.pdf`,
      mimeType: 'application/pdf',
      encoding: 'utf-8',
}];
cy.get('ngx-dropzone')
      .should('exist')
      .attachFile(files, { subjectType: 'drag-n-drop' });
```

### Versions

```
"ngx-dropzone": "^2.4.0",
"cypress-file-upload": "^5.0.4",
"cypress": "^7.0.0",
```

**Comment by abramenal** [comment]
Hi @MikeDabrowski 
Thanks for submitting the issue!

I think it is related to #290

**Comment by abramenal** [comment]
@MikeDabrowski `v5.0.5` is just released, can you please check if this issue still persists?

**Comment by MikeDabrowski** [comment]
@abramenal I can confirm it works with `v5.0.5`. Good catch!
