### ISSUE TITLE
[Bug] Not adding file correctly "[object Promise]" contents always

### ISSUE THREAD

**Issue by philjones88** [abramenal/cypress-file-upload#51]
### Current behavior:

```
cy.get('input').upload(
      [{
        fileContent: 'foobar',
        fileName: 'dynamic.lic',
        mimeType: '',
        encoding: 'utf-8'
      }],
      {
        force: true,
        subjectType: 'drag-n-drop'
      });
```

Against an ng2-file-upload target https://github.com/valor-software/ng2-file-upload

The HTTP request then made by angular is:

```
------WebKitFormBoundaryuPJXUTfgfFPBd4cB
Content-Disposition: form-data; name="file"; filename="dynamic.lic"
Content-Type: application/octet-stream

[object Promise]
------WebKitFormBoundaryuPJXUTfgfFPBd4cB--
```

Which is wrong as it should be the file contents.

The angular app logging shows the file in ng2-file-upload as:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/677167/55405552-3ec09b00-5552-11e9-86aa-b89ea3c9778f.png">

### Desired behavior:

Should add the file properly

### Steps to reproduce: (app code and test code)

Maybe try targeting these demo controls https://valor-software.com/ng2-file-upload/

### Versions

Cypress 3.2.0
MacOS latest
Node LTS
Chrome

**Comment by philjones88** [comment]
Was able to workaround it by using this approach from the thread I found this package in:

https://github.com/cypress-io/cypress/issues/170#issuecomment-477421775

**Comment by abramenal** [comment]
@philjones88 thanks for submitting the issue!

The only thing I've spotted is this async handlers mapping that may not work as we want it to:
https://github.com/abramenal/cypress-file-upload/blob/master/src/helpers/getFileBlob.js#L3

Will take a look later today if that is the cause, cuz the rest is actually the same as on the solution you mentioned, just encapsulated in the plugin.

**Comment by abramenal** [comment]
@philjones88 can you try out v3.0.7 I've just published? It should solve the issue.

**Comment by abramenal** [comment]
If your thing is fixed, I think it might be good to have a separate example folder for angular components related to file upload (like ng2-file-upload you mentioned).

**Comment by philjones88** [comment]
@abramenal nice work, 3.0.7 works with `drag-n-drop` approach :) <3

**Comment by abramenal** [comment]
Yay perfect!
@allcontributors[bot] add @philjones88 for bug

**Comment by abramenal** [comment]
Will work on angular examples later on. Stay tuned :)
