### ISSUE TITLE
[Bug] pdf upload not working

### ISSUE THREAD

**Issue by NicolasGehring** [abramenal/cypress-file-upload#58]
### Current behavior:
When uploading a pdf and having a file name with .pdf it throw TypeError: Cannot read property 'message' of undefined. After a lot of time i found out that the error occurs when a filename with extension .pdf is submitted. changing file extension to e.g. .jpg fixes the problem.

### Desired behavior:
Pdf upload should work without problems

To upload a file with pdf ending 
### Steps to reproduce: (app code and test code)
```
//testFile is .pdf file
   cy.fixture('dataMocks.js').then(mocks => {
      cy.fixture(mocks.testFile, 'base64').then(fileContent => {
        cy.get('[data-cy="dropZoneFiles"]').upload(
          { fileContent, fileName: 'test.pdf', mimeType: 'application/pdf' },
          { subjectType: 'drag-n-drop' },
        );
      });
```

**Comment by Mobiletainment** [comment]
I just had the same issue and can confirm this problem.
Your workaround seems to work for the moment.

**Comment by kmui2** [comment]
@abramenal, it seems that the default encodings doesn't include pdf and then throws an error message.
https://github.com/abramenal/cypress-file-upload/blob/5f0513326c98bd9df599280c3cb41696e9787fe3/src/helpers/getValidEncoding.js#L7-L29

There is, however, an additional issue concerning `ERR_TYPES.UNABLE_TO_DECODE`. This isn't defined in `errorTypes.js`:
https://github.com/abramenal/cypress-file-upload/blob/5f0513326c98bd9df599280c3cb41696e9787fe3/src/error/errorTypes.js#L1-L10

The best workaround as of now for you guys, @NicolasGehring and @Mobiletainment, would be to include the encoding parameter (https://github.com/abramenal/cypress-file-upload#api). It should either be `utf8` or `base64`.

**Comment by abramenal** [comment]
Hi @NicolasGehring 

Thanks for submitting the issue!
@kmui2 you are correct, the best way to work with that is optional `encoding` parameter that was created exactly for such purpose.

I've added built-in PDF support as well. It's now released with v3.0.8

**Comment by abramenal** [comment]
@allcontributors[bot] add @kmui2 for review

**Comment by abramenal** [comment]
@allcontributors[bot] add @NicolasGehring for bug

**Comment by abramenal** [comment]
@allcontributors[bot] add @Mobiletainment for question

**Comment by abramenal** [comment]
Maybe it worth updating README.md as well to make a workaround with `encoding` more clear..
