### ISSUE TITLE
[Bug] failed to upload a vcf file

### ISSUE THREAD

**Issue by xiaomeidan** [abramenal/cypress-file-upload#66]
### Current behavior:
```
cy.fixture('user.vcf').then(fileContent =>
        {
          cy.get('input[type="file"]').upload(
            { fileContent, fileName: 'user.vcf', mineType: 'base64' },
            { subjectType: 'input' },
          );
        });
```
![image](https://user-images.githubusercontent.com/5284575/56565118-36ec9780-65e2-11e9-8c95-cadc0b9ff18b.png)

### Desired behavior:
upload a vcf file

### Steps to reproduce: (app code and test code)
get a vcf file, thanks

### Versions
Cypress: 3.1.5
OS: Windows10 professional
browser: Chromium 75

**Comment by abramenal** [comment]
Hi @xiaomeidan 
Thanks for submitting the issue.

At first, the mime type you're passing is not correct. It should be somewhat like `text/vcard`.

Have you tried providing `encoding` for the file manually, as the message suggests? See https://github.com/abramenal/cypress-file-upload#api
It depends on what vcard files you're using, but most likely it is in utf-8.

I suppose it should be as follows:

```
cy.fixture('user.vcf').then(fileContent => {
  cy.get('input[type="file"]').upload(
    { fileContent, fileName: 'user.vcf', mineType: 'text/vcard', encoding: 'utf8' },
    { subjectType: 'input' },
  );
});
```

Check this out and let me know if that works or not. After that we'll make a PR that adds built-in support for this type of files (like we did for PDF: https://github.com/abramenal/cypress-file-upload/pull/59/files)

**Comment by xiaomeidan** [comment]
@abramenal thanks a lot, your suggestion works well

**Comment by abramenal** [comment]
@xiaomeidan happy to hear! Do you have any suggestions of how to make the error messaging more clear? Like if someone else will be stucked with the same error?

**Comment by abramenal** [comment]
@allcontributors[bot] add @xiaomeidan for bug

**Comment by xiaomeidan** [comment]
@abramenal I recheck this error message, it's clear enough, it's my bad not to check api carefully.
Besides, my code is not working without encoding, i'm in 3.1.5

**Comment by abramenal** [comment]
@xiaomeidan you should install `cypress-file-upload@3.1.1` first

**Comment by xiaomeidan** [comment]
@abramenal you r right, thanks, working after upgrade cypress-file-upload

**Comment by jeffradom** [comment]
I also, have an issue with the uploading of VCF file which I thought is just a regular text file in my opinion
I had used this code and please let me know what might be wrong in my code?  I use Chrome version 75
  cy.fixture(vcf_fileNameAndPath).then(fileContent => {
            cy.xpath(selector).upload(
              { fileContent, vcf_fileNameAndPath, mimeType: 'text/plain' },
              {subjectType: 'input' }
            );
          });

**Comment by abramenal** [comment]
@jeffradom 
the issue is in `.upload` first parameter – it should be an object with `fileName`, `fileContent` and `mimeType` at least. See https://github.com/abramenal/cypress-file-upload#api

Please also note that `fileName` should not contain the path to file, only it's name with extension

**Comment by jeffradom** [comment]
sorry, i didn't get it after looking into the sample code. Is fileContent is wrong?  Please, clarify

Thanks

Jeff

**Comment by jeffradom** [comment]
is this from above code correct?
cy.fixture('user.vcf').then(fileContent => {
  cy.get('input[type="file"]').upload(
    { fileContent, fileName: 'user.vcf', mimeType: 'text/vcard', encoding: 'utf8' },
    { subjectType: 'input' },
  );
});

And what will be a syntax when I want to use file name as a variable?

**Comment by abramenal** [comment]
@jeffradom 
Let's see your example:
```
const vcf_fileNameAndPath = 'folder1/test.vcf';
cy.fixture(vcf_fileNameAndPath).then(fileContent => {
cy.xpath(selector).upload(
{ fileContent, vcf_fileNameAndPath, mimeType: 'text/plain' },
{subjectType: 'input' }
);
});
```

I think in your case the code should be as follows:
```
const vcf_fileName = 'test.vcf'
const vcf_fileNameAndPath = `vcfs/${vcf_fileName}`;

cy.fixture(vcf_fileNameAndPath).then(fileContent => {
cy.xpath(selector).upload(
{ fileContent, fileName: vcf_fileName, mimeType: 'text/plain' },
{subjectType: 'input' }
);
});
```

Please see the difference. The problem is with `fileName` property you pass – it should contain only name, not path.

**Comment by jeffradom** [comment]
I'm using this code now and it works but sometimes file uploaded is corruct.  Can you suggest something
 selector = '//input[@placeholder="VCF File Input"]';
      
       cy.fixture(vcf_fileNameAndPath).then(fileContent => {
            cy.xpath(selector).upload(
              { fileContent, fileName: vcf_fileName, mimeType: 'text/vcard', encoding: 'utf8' },
              {subjectType: 'input' }
            );
          });

I had used Selenium based tool for the same flow and it always worked.  It was only one line and file is really small

**Comment by jeffradom** [comment]
'll use this code to upload a file cy.fixture(vcf_fileNameAndPath).then(fileContent => {
cy.xpath(selector).upload(
{ fileContent, fileName: vcf_fileName, mimeType: 'text/vcard', encoding: 'utf8' },
{subjectType: 'input' }
);
}); I see that randomly it corrupts a file or interrupt uploading because of some delay. I see data errors once a page is saved. CAn somebody help me and suggest something?

**Comment by abramenal** [comment]
@jeffradom 
That really depends on your case.
At first, please provide any error messages / stacktraces you get. If you can make a short video and upload it somewhere I can say more about the delays you experience.
You should also check if your file is encoded in UTF-8, otherwise encoding should be different.
At last, this seems to be more of some specific issue with your code and/or fixture file, not the plugin itself – as you see above, we have a working example and some users who use it. Anyway let's try fixing your case.

**Comment by jeffradom** [comment]
is it any difference between utf8 and utf-8 encodings?

**Comment by abramenal** [comment]
@jeffradom nope

**Comment by jeffradom** [comment]
will your plugin support BAM file extension which is a combination of binary and text.  It's one of health since the defacto industry standard like VCF files.  Please, let me know

**Comment by abramenal** [comment]
@jeffradom 
Let's see.. can you try to upload it with `mimeType` set to 'application/octet-stream' and `encoding` set to 'binary'?

**Comment by jeffradom** [comment]
Can I upload BAM files which are mix of binary and text and defacto  health industry standard?  If I can what should I use for Mime type and encoding?  Please, confirm

**Comment by abramenal** [comment]
@jeffradom as I told you above, the values are:
mime type: "application/octet-stream"
encoding: "binary"
