### ISSUE TITLE
[Bug] Force download

### ISSUE THREAD

**Issue by tbigueres** [abramenal/cypress-file-upload#75]
### Current behavior:

I try to upload a file into a hidden input (with display:none).
I've first tried it using the subjectType input : 

`    cy.fixture(image1).then(fileContent => {
      cy.get('.popupContent form input[type=file]').upload(
          { fileContent, fileName: image1, mimeType: 'application/pdf' },
          { subjectType: 'input', force:true },
      );
    });
`

But I got the following error : 
![image](https://user-images.githubusercontent.com/2139076/59094124-c9889200-8915-11e9-98eb-a358b17905ef.png)

![image](https://user-images.githubusercontent.com/2139076/59094148-d60cea80-8915-11e9-96b6-90dc5c6da7dd.png)

I tried then without the fileName option, by adding directly the variable 

` cy.fixture(image1).then(fileContent => {
      cy.get('.popupContent form input[type=file]').upload(
          { fileContent, image1, mimeType: 'application/pdf' },
          { subjectType: 'input', force:true },
      );
    });`

![image](https://user-images.githubusercontent.com/2139076/59094287-1704ff00-8916-11e9-9633-db978dfbb774.png)

![image](https://user-images.githubusercontent.com/2139076/59094325-2ab06580-8916-11e9-9ed8-384f3ca6506d.png)

So I changed my mind and tried to use drag-and-drop to see if this would work.

`    cy.fixture(image1).then(fileContent => {
      cy.get('.popupContent form input[type=file]').upload(
          { fileContent, fileName: image1, mimeType: 'application/pdf' },
          { subjectType: 'drag-n-drop', force:true },
      );
    });`

I was nearly there when I noticed that drag-and-drop didn't implemented the force option.

![image](https://user-images.githubusercontent.com/2139076/59094433-68ad8980-8916-11e9-9d7e-e7d00edf2191.png)

So the new error was : 

![image](https://user-images.githubusercontent.com/2139076/59094526-998dbe80-8916-11e9-9a6b-f2469c99075a.png)

### Desired behavior:

I guess that fixing the input error (which I don't really know how to) and implementing force on drag and drop handler would be awesome. 

### Steps to reproduce: (app code and test code)
--
--
### Versions

Cypress : 3.3.1
cypress-file-upload : 3.1.2
Chromium 57

**Comment by abramenal** [comment]
Hi @tbigueres 
Thanks for submitting the issue!

Regarding case 1: can you please share `image1`? It should be like "myawesomeimage.jpg" – maybe in your case it contains a path to the file, maybe something else. Let's try figuring that out.

Regarding case 2: great catch! never thought it would be needed. This needs to be fixed

**Comment by tbigueres** [comment]
Hi @abramenal 

image1 = "assets/image.jpg";
I've tried moving the image to the root of fixtures and removing assets it still doesn't work. 
I also tried it with any other the file and it works with drag-and-drop but not with input. So not sure about the filename stuff. 

Let me know if I can help you !

**Comment by tbigueres** [comment]
Concerning the illegal Constructor thing, here is where the error happens : 

![image](https://user-images.githubusercontent.com/2139076/59228064-28c8f980-8bd7-11e9-82a1-9d2f21da9b53.png)

**Comment by tbigueres** [comment]
Just do know, do you know when you'll be able to modify at least the force state for drag-and-drop ? 

Thanks !

**Comment by abramenal** [comment]
@tbigueres thanks for sharing that.
I consider this as a critical thing so will do that within 2 days – hopefully releasing this tomorrow.

While waiting for the fix I still recommend you to take a look on the examples with plain input (it's located in a separate folder in the repo) to see what can cause this issue – your case seems to be really straightforward but somehow does not work for you.

**Comment by tbigueres** [comment]
Perfect thanks for the answer, I'll check that and let you know.

**Comment by abramenal** [comment]
@tbigueres v3.1.3 is out!
Can you please test this on your solution with forced drag-n-drop upload?
