### ISSUE TITLE
[Bug] Doesn't fail on non-input targets

### ISSUE THREAD

**Issue by 0xADD1E** [abramenal/cypress-file-upload#82]
### Current behavior:

When I pass something other than an input to upload (specifically a div containing an input), the library simply ignores it and acts like things are working correctly

### Desired behavior:

Fail when invalid targets are passed

### Versions

Cypress 3.3.1, Fedora Linux, Chrome 73

**Comment by abramenal** [comment]
Hi @0xADD1E 
That's a good catch and definitely a thing to improve.
Thanks for the feedback, will chase that soon!

**Comment by abramenal** [comment]
@all-contributors add @0xADD1E for bug

**Comment by abramenal** [comment]
Fixed in v3.3.0!
