### ISSUE TITLE
Question: Why is the distributable so large?

### ISSUE THREAD

**Issue by aleccool213** [abramenal/cypress-file-upload#84]
<img width="524" alt="Screenshot at Jul 05 14-05-07" src="https://user-images.githubusercontent.com/6475934/60738940-043e1400-9f2e-11e9-8855-c0414ced4f5e.png">

Just wondering! Thanks

**Comment by abramenal** [comment]
Hi @aleccool213 
Thanks for asking!

That was definitely an issue, I was working on some recipes stuff and somehow published all this stuff (even including node_modules for it). Fixed that in v3.2.1 and added you to our contributors list.
Cheers!

**Comment by abramenal** [comment]
Btw @aleccool213 what is the tool you use for seeing package's size?

**Comment by aleccool213** [comment]
@abramenal 

We use https://www.npmjs.com/package/@microsoft/rush for installing our packages. The very large ones show up in a separate progress bar and I just happened to notice this. Was by chance!
