### ISSUE TITLE
PDF upload returning unsupported fileOrArray value error even with encoding workaround

### ISSUE THREAD

**Issue by ChaseBig** [abramenal/cypress-file-upload#92]
I have reviewed this reported issue given that it is very similar to my error but the encoding workaround does not seem to be working for me. https://github.com/abramenal/cypress-file-upload/issues/58  Any help would be great! 

I've followed the steps on the README but have not been able to figure out my issue yet. I'm still quite new to Cypress and javascript in general, so I apologize if I'm missing something obvious. I added and am fetching `[name="cy-dropzone"]` rather than `data-cy=...` as shown in the readme example. I have attempted to use `utf8` _and_ `base64` but neither worked.

**Experiencing this error:** 
` [cypress-file-upload error]: One or more field is invalid within given file(s).
Please look into docs to find supported "fileOrArray" values`

**Current code block**
```
    const fileName = 'testFile.pdf';
    cy.fixture(fileName).then(fileContent => {
      cy.get('[name="cy-dropzone"]', { force: true }).upload(
        { force: true },
        { fileContent, fileName, mimeType: 'application/pdf', encoding: 'base64' },
        { subjectType: 'drag-n-drop', force: true },
      );
    });
```
<img width="1009" alt="Screen Shot 2019-07-24 at 8 08 03 AM" src="https://user-images.githubusercontent.com/10504626/61796199-8bbeca80-adea-11e9-85ec-5425ed29e12a.png">

**Comment by abramenal** [comment]
Hi @ChaseBig 
Thanks for submitting the issue.
That's totally fine, I'm open for any help related to the plugin.

The problem in your code is quite simple: you just should follow the API guide in README.
upload function receives 2 arguments: 1st is file object, 2nd is options object.
So your code should look like:


```
const fileName = 'testFile.pdf';
    cy.fixture(fileName).then(fileContent => {
      cy.get('[name="cy-dropzone"]', { force: true }).upload(
        { fileContent, fileName, mimeType: 'application/pdf', encoding: 'base64' },
        { subjectType: 'drag-n-drop' },
      );
    });
```

Please try out this, and if it does not work, likely you should add `force` parameter (in case if your dropzone is overlapped by something else), like:

```
const fileName = 'testFile.pdf';
    cy.fixture(fileName).then(fileContent => {
      cy.get('[name="cy-dropzone"]', { force: true }).upload(
        { fileContent, fileName, mimeType: 'application/pdf', encoding: 'base64' },
        { subjectType: 'drag-n-drop', force: true },
      );
    });
```

Let me know whether the issue is fixed for you, otherwise I'm happy to look further.

**Comment by ChaseBig** [comment]
Thanks for the quick reply, @abramenal! 

Again, I apologize for any dumb questions. But I guess I'm a bit confused at the difference between my block of code in the issue description and the blocks of code you posted in your reply.  My comparison mostly just shows that you have slightly different `{ force: true }` flags. It looks like I had all the necessary arguments set in my initial block of code, correct? Or am I missing something?

Thank you again for your help!

**Comment by abramenal** [comment]
@ChaseBig the difference is in `{ force: true }` you placed on the first place, you are right.
Internally the function expects its arguments being passed in correct order.

What you did is passed actually 3 arguments (this object, file contents object, and options object) which is not correct. Thus, function internally sees that passed 1st argument is not a file but something else and throws.
Does that make sense?

**Comment by ChaseBig** [comment]
@abramenal Ohhhh I see now! Yes, that makes perfect sense. I appreciate you being patient and taking a moment to help explain that to me a little better!

**Comment by ChaseBig** [comment]
@abramenal I am now having a different issue with encoding characters. Do I need to open a new issue ticket for this? I've attached a screenshot of the error along with a copy of the testFile.pdf. 

```InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded contains characters outside of the Latin1 range.```

<img width="994" alt="Screen Shot 2019-07-24 at 9 34 42 AM" src="https://user-images.githubusercontent.com/10504626/61802631-6cc63580-adf6-11e9-85df-008dd8846bc9.png">

[testFile.pdf](https://github.com/abramenal/cypress-file-upload/files/3427312/testFile.pdf)

**Comment by abramenal** [comment]
@ChaseBig 

So right, if that is a plain PDF, the code should look like:
```
    const fileName = 'testFile.pdf';
    cy.fixture(fileName).then(fileContent => {
      cy.get('[name="cy-dropzone"]', { force: true }).upload(
        { fileContent, fileName, mimeType: 'application/pdf' },
        { subjectType: 'drag-n-drop', force: true },
      );
    });
```

the difference is that you basically let the plugin decode PDF naturally (rather than explicitly using base64 which is wrong).

Internally it does some basic mapping based on given file extension
https://github.com/abramenal/cypress-file-upload/blob/master/src/helpers/getEncoding.js
so usually you don't even need to put this `encoding` explicitly. It is kept for more complex cases with weird file extensions that are rarely used and won't be recognized automatically.

Please let me know if that works.

**Comment by ChaseBig** [comment]
@abramenal Perfect! Thank you so much. It's working great now.

Thank you thank you thank you! 🙏

**Comment by lamqson** [comment]
@abramenal , I use your code as follow:
```
      const fileName = 'Basic-Non-Disclosure-Agreement.pdf'
      cy.fixture(fileName).then((fileContent) => {
        cy.get('input[type=file]').upload(
          { fileContent, fileName, mimeType: 'application/pdf' },
          { subjectType: 'drag-n-drop', force: true }
        )
      })
```
But I got error:
```
cypress_runner.js:200347 InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
at b64toBlob (http://localhost:3000/__cypress/tests?p=cypress/support/index.js:211:24)
```
<img width="798" alt="Screen Shot 2020-10-21 at 2 50 05 PM" src="https://user-images.githubusercontent.com/54222499/96791331-1e169b00-13ad-11eb-84ce-e41af23bec25.png">

Could you help to see what would be the problem? Thanks.

**Comment by abramenal** [comment]
@lamqson hi there!
Can you please try either using shorthand, or setting encoding explicitly? I'm not sure which one works for you, so please let me know.

shorthand:
```
const fileName = 'Basic-Non-Disclosure-Agreement.pdf'
      cy.fixture(fileName).then((fileContent) => {
        cy.get('input[type=file]').upload(
          fileName,
          { subjectType: 'drag-n-drop', force: true }
        )
      })

```

explicitly set encoding value:
```
const fileName = 'Basic-Non-Disclosure-Agreement.pdf'
      cy.fixture(fileName).then((fileContent) => {
        cy.get('input[type=file]').upload(
          { fileContent, fileName, mimeType: 'application/pdf', encoding: 'utf-8' },
          { subjectType: 'drag-n-drop', force: true }
        )
      })

```
