### ISSUE TITLE
[Feature] In the GUI, show the number line of code being run rather than the step number

### ISSUE THREAD

**Issue by ChaseBig** [abramenal/cypress-file-upload#93]
### Current behavior:

When viewing running tests via the GUI or recordings online, there is a number associated with each step. This isn't really helpful for any of my personal use-cases and I'm unsure if it's really that helpful for anyone else. 

<img width="301" alt="Screen Shot 2019-07-25 at 10 10 06 AM" src="https://user-images.githubusercontent.com/10504626/61886423-520ec200-aec5-11e9-8a5d-0b5f4cf46e87.png">

### Desired behavior:

Would WOULD be sooooo helpful is if the number shown in the GUI for each step was in reference to the specific line of code being run. This would help to easily debug which specific line of the test is failing. 
<img width="301" alt="Screen Shot 2019-07-25 at 10 10 06 AM" src="https://user-images.githubusercontent.com/10504626/61886662-baf63a00-aec5-11e9-91a3-0b2d83e691f3.png">
 

### Versions

Cypress 3.4.0
OSX 10.14.6
Chrome 75
Electron 61

**Comment by abramenal** [comment]
Hi @ChaseBig 
Thanks for submitting the issue!

As far as I'm concerned this is an internal Cypress feature, not really the plugin's one.
Thus, I cannot affect such behavior.
Please let me know if there's something else I can help you with.

**Comment by ChaseBig** [comment]
Hi @abramenal! 

Thank you for replying.

When I click "New Issue", it asks me if I want to submit an issue or submit a feature request. I was intending to submit a new "feature request" rather than an actual "Issue". Do you know where the best place for me to submit this feature request would be?

**Comment by abramenal** [comment]
@ChaseBig I believe it's https://github.com/cypress-io/cypress

**Comment by ChaseBig** [comment]
@abramenal I'm an idiot 🤦‍♂ I didn't realize I had submitted this on the cypress-file-upload repo. My apologies.

**Comment by abramenal** [comment]
@ChaseBig that's fine 😄
