### ISSUE TITLE
[Feature] Does upload.() return a promise?

### ISSUE THREAD

**Issue by kyledavelaar** [abramenal/cypress-file-upload#97]
### Desired behavior:

Great library!  Thanks for making this.  Not sure if this is a bug or could be a new feature.  I'd like upload() to wait until the file has been uploaded and then do something like click a button on the page. In the code below it seems that upload() is not waiting for the file to finish uploading before going into the second .then() block. 

### Current behavior:

`cy.fixture('./3row.csv').then(fileContent => {
      cy.get('input[type="file"]').upload({
        fileContent,
        fileName: './3row.csv',
        mimeType: 'text/csv'
      }).then(content => {
        cy.get('[data-cy="map-headers-container"]').contains('NEXT').click({force: true});
      })
    });
  })`

### Versions

cypress 3.4

**Comment by abramenal** [comment]
Hey @kyledavelaar 
Thanks for submitting the issue!

We discussed that stuff in #91, here's the answer:

> I think the upload process you mention is more about waiting network request to complete – correct me if I'm wrong.
If that is correct, the only way to do it properly is:
https://docs.cypress.io/api/commands/wait.html#Wait-for-a-specific-XHR-to-respond

**Comment by kyledavelaar** [comment]
Hi @abramenal
Thanks for the response.  Unfortunately I am not needing to wait for an xhr request but for the file to be uploaded.  In my app after I upload the file, I show data on the screen about the file, row mappings (it's a csv file), etc. and I find that when I immediately have cypress look for them after the upload(), they are not there yet.  Currently I am doing a cypress.wait(500) but I'd like to avoid that if possible via a promise or something like cypress does with xhr aliases.

**Comment by abramenal** [comment]
@kyledavelaar 
Oh I see what you mean. Yes, then likely I need to go through the Promise chain in order to resolve it properly – will likely pick that up this week.

**Comment by kyledavelaar** [comment]
Cool thanks so much

**Comment by abramenal** [comment]
@kyledavelaar 
Can you tell what version of `cypress-file-upload` you're using?
Also, what is the size of that CSV you're uploading?
And finally, what is this `data-cy="map-headers-container"` component?


I feel a bit of misconception here. Ideally you don't need to control the async flow this way – Cypress does that for you for most cases. See 
https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Noisy-Promise-demonstration-Not-valid-code

So can you try out this:

```
cy.fixture('./3row.csv').then(fileContent => {
  cy.
      get('input[type="file"]')
      .upload({ fileContent, fileName: './3row.csv', mimeType: 'text/csv' });
});

cy
  .get('[data-cy="map-headers-container"]')
  .contains('NEXT')
  .click({ force: true });
```

After that, the problem I see here is that your `data-cy="map-headers-container"` component might not receive/render data you need immediately when the plugin inserts it (or at least does it in async way). So same thing here, ideally Cypress will resolve async stuff automatically.

If we omit async part, `cy.contains` command also has timeout value as time for your data to appear (before the whole command gets rejected. See https://docs.cypress.io/api/commands/contains.html#Arguments

Waiting for your reply.

**Comment by kyledavelaar** [comment]
Sorry was out on holiday and couldn't investigate more.  I see what you mean about the way Cypress handles async.  To answer your questions I'm using the latest version of cypress-file-upload, the size of the csv is 88 bytes, and the data-attribute is for the container that holds the NEXT button.

**Comment by abramenal** [comment]
@kyledavelaar is the issue still relevant to you?
If yes, you could take a look on #104 bug description, there is a nice way to do the thing which is likely to be same as yours.
If that does not help still, please reopen this one with details.

**Comment by kyledavelaar** [comment]
Hi thanks for asking.  Feel free to close the issue.

**Comment by BavithraDuraisamy** [comment]
> @kyledavelaar
> Can you tell what version of `cypress-file-upload` you're using?
> Also, what is the size of that CSV you're uploading?
> And finally, what is this `data-cy="map-headers-container"` component?
> 
> I feel a bit of misconception here. Ideally you don't need to control the async flow this way – Cypress does that for you for most cases. See
> https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Noisy-Promise-demonstration-Not-valid-code
> 
> So can you try out this:
> 
> ```
> cy.fixture('./3row.csv').then(fileContent => {
>   cy.
>       get('input[type="file"]')
>       .upload({ fileContent, fileName: './3row.csv', mimeType: 'text/csv' });
> });
> 
> cy
>   .get('[data-cy="map-headers-container"]')
>   .contains('NEXT')
>   .click({ force: true });
> ```
> 
> After that, the problem I see here is that your `data-cy="map-headers-container"` component might not receive/render data you need immediately when the plugin inserts it (or at least does it in async way). So same thing here, ideally Cypress will resolve async stuff automatically.
> 
> If we omit async part, `cy.contains` command also has timeout value as time for your data to appear (before the whole command gets rejected. See https://docs.cypress.io/api/commands/contains.html#Arguments
> 
> Waiting for your reply.

i'm getting this error when trying to upload csv file
passed subject element is not valid.

**Comment by abramenal** [comment]
Hi @BavithraDuraisamy 
Let's create a new issue where you describe your setup with code snippets so I can help you quickly
