### ISSUE TITLE
[Bug] Tests using upload are crashing on jenkins/electron

### ISSUE THREAD

**Issue by leorigon** [abramenal/cypress-file-upload#99]
Tests should be concluded with success like happens on chrome locally. But in our CI, jenkins, tests are be crashing, the CI don't continued tests after call the upload command. The same problem happens on terminal/electron execution. The test is passing, but not continued to the next step. It's freeze :( 

        Given('I have an image {string} and I put on {string}',
            (fileName: string, input: string) => {
                 cy.fixture(fileName).then(fileContent => {
                      const [, ext] = fileName.split('.')
                      
                      cy.get(`input[name="${input}"]`).upload(
                            {
                                fileContent,
                                fileName,
                                mimeType: `image/${ext}`,
                                encoding: 'base64'
                            },
                           { subjectType: 'input' }
                       )
                 })
         })

We use cypress, 3.2 and cypress-cucumber-preprocessor.

**Comment by abramenal** [comment]
Hi @leorigon 
Thanks for submitting the issue!

Could you please also tell what setup you use for your frontend? It is likely the problem with compatibility with that I feel.

**Comment by abramenal** [comment]
@leorigon are you using plain HTML5 input for file upload? Or component from some package?

**Comment by abramenal** [comment]
Hey @leorigon 
Is the issue still relevant to you? Now I finally have time to take a look on the plugin, had a long vacation 😈 
I'm doing package cleanup now so will close the issue for now. Please feel free to reopen it if the issue still relevant so we could find out its cause and fix. Thanks for understanding 🙏

**Comment by ChandraPuvendhan** [comment]
Still issue exists. Please check on the same. [Bug]Tests using upload are crashing on jenkins #128
